### ISSUE TITLE
Design signup form

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1]

**Comment by jimmynotjim** [comment]
Added to the Wireframes, under `Standard Desktop`, first row, first column

**Comment by JoshSmith** [comment]
![join](https://cloud.githubusercontent.com/assets/321667/15060619/3f74da9a-12e1-11e6-824f-61ddacba7e10.png)

**Comment by JoshSmith** [comment]
![sign up](https://cloud.githubusercontent.com/assets/321667/15309203/996822bc-1b99-11e6-84f1-150bcb18d1d5.png)
