### ISSUE TITLE
Post author usernames aren't showing up on the project post list anymore

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#100]

**Comment by begedin** [comment]
I'm not really sure what the problem here could be. 

My assumption is, when rendering the list of posts, each post has a user relationship, but the related user record hasn't been fetched yet, so we only have the ids, not the usernames. Still they should be fetched at some point and they should display once they are fetched, so I'm not sure what the exact issue is.

**Comment by JoshSmith** [comment]
Closed by https://github.com/code-corps/code-corps-api/pull/250
