### ISSUE TITLE
Transitioning during signup while photo is uploading fails

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1009]
# Problem

- When on `start/hello`, started uploading a photo.
- Hit submit button to transition to `start/interests`.
- Successful transition to `start/interests`.
- Photo finishes uploading and Ember tries to `PATCH /users/:id`.
- User has the following attributes:

```
{
  "data": {
    "attributes": {
      "cloudinary-public-id": "gogsd44pqghib04nk0fz",
      "state": "edited_profile",
      "state-transition": "edit_profile"
    },
  }
}
```

This results in a `422` error because we're attempting to transition from `edited_profile` to `edited_profile` via the `edit_profile` transition, which is not allowed.

**Comment by JoshSmith** [comment]
https://sentry.io/code-corps/code-corps-ember/issues/211853713/

**Comment by JoshSmith** [comment]
https://sentry.io/code-corps/code-corps-ember/issues/212194093/

**Comment by snewcomer** [comment]
@JoshSmith I can tackle this one.  Is the thought to prevent transition until photo has uploaded?

**Comment by JoshSmith** [comment]
@snewcomer I think that's probably the correct way of handling it, yeah.

**Comment by JoshSmith** [comment]
I think we can just disable the button if the photo is uploading.

**Comment by snewcomer** [comment]
@JoshSmith don't see any tests for the hello page.  Looking to test this, so didn't know if I should create one, move the markup to a a component and integration test, or just leave it w/o a test.

**Comment by JoshSmith** [comment]
@snewcomer there are tests in acceptance onboarding, I believe.

**Comment by snewcomer** [comment]
I will finish this today.
