### ISSUE TITLE
Refactor skills-list service duplicated code into Mixin

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-ember#1019]
# Problem
We have a few skills-list related services that have duplicated code. Seeing as we'll be adding more of these services, it would be great to refactor the shared logic/code into a mixin. 👌 :handshake: 

## List of Services
- [project-skills-list](https://github.com/code-corps/code-corps-ember/pull/1014/files#diff-96196fd3c9871bfda914d73e97a13e12)
- [user-skills](https://github.com/code-corps/code-corps-ember/blob/develop/app/services/user-skills-list.js)

## References
- #1014 
- #1011

**Comment by begedin** [comment]
@JoshSmith Looking at `project-skills-list`, `user-skills-list` and `task-skills-list`, yes, a mixin would reduce some duplication.

However, it would not be much and it would be at the cost of clarity. 

Additionally, there is a discussion in #1161 about potentially eliminating these services and relying on `DS.PromiseArray` facilities instead.

My vote is on closing this. Reducing code base by removing duplication is great, but only when the benefit is clearer code. I don't think that would be the case here.

**Comment by JoshSmith** [comment]
@begedin okay, agreed on this, but I do think we should have more discussion in #1161 still.
