### ISSUE TITLE
Negative Donation Goal Permitted

### ISSUE THREAD

**Issue by Dubhghlas** [code-corps/code-corps-ember#1029]
# Problem

Although the text input fields are set to "number" and some have the attribute "min" set to 0, you are still able to input a negative dollar amount manually. I found an input in `/app/templates/components/donation-goal-edit.hbs` that did not have the "min" attribute set.

![capture](https://cloud.githubusercontent.com/assets/5733906/22811270/c2c0740c-ef0b-11e6-9820-78a8c609d672.JPG)

# Potential Fixes

- At a minimum, the "Create Goal" or "Save Changes" button should not allow the information to be saved when the input field is not within the valid range.
- A better solution might be to signal the invalid dollar amount upon entry - perhaps when the field loses focus - and zero out the field.
- All fields should have min="0" set.

# Working On...

- I'm clearing up the attribute problem at the moment.
- I'm not comfortable with Ember yet and so I'm not sure on the proper way to perform this validation in an "Ember way".

**Comment by JoshSmith** [comment]
@Dubhghlas can you also add an issue into the API? Good for us to have validation there, as well.

**Comment by JoshSmith** [comment]
Closed by #1030.
