### ISSUE TITLE
Consider replacing our custom CC form with Stripe Elements wrapped component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1070]
# Problem

Stripe recently launched [Stripe Elements](https://stripe.com/docs/elements) to allow for a configurable UI component that can be dropped into an application. This looks smoother than our current component and would reduce the work we would need to do to maintain it.

One additional upside is that the design of this component would bring the "user already has card UI" closer to the new form. This also removes a lot of the heavy-lifting on our part in terms of populating Stripe errors, Stripe validations, etc.

There's a lot of vanilla JS here but that's not really a bad thing. We could easily release an `ember-stripe-elements` to complement `ember-stripe-service`. This component then would wrap the element and provide a testable, configurable component for people to drop into their Ember apps.

I've created [a repo here](https://github.com/code-corps/ember-stripe-elements) in case we want to do this.

Here's [a JSFiddle](https://jsfiddle.net/Lm9qg3ad/) to play around with it. Note that you do need to add your public key to this, and would not recommend saving the fiddle with your public key provided.

**Comment by JoshSmith** [comment]
@begedin what do you think about doing this?

**Comment by begedin** [comment]
Objectively, it's probably better to use the official package compared to one of our own.

Outside of that, I'm not sure. It depends on a lot of things:

- how much more we want to do with our existing form
- how much time the library would save us in that area
- how much work will it be to integrate into ember
- where it is on our plan/priority list
- added value/exposition of being a maintainer of another stripe library
- how it connects with what our API does

I think we we just use the library as a blackbox, with the proposed ember addon being just an interface between it and the app consuming it, it should not take too long to get it in. I guess there's an initial hurdle to overcome with that, but once we're past it and we got it working, it's just a matter of maintaining the addon so it's up to date with the library.

**Comment by begedin** [comment]
To add, I also see vanilla js as a good thing. Makes it that much easier to integrate with ember.

**Comment by JoshSmith** [comment]
Done by building and using `ember-stripe-elements`.
