### ISSUE TITLE
Task Page only shows current user

### ISSUE THREAD

**Issue by npendery** [code-corps/code-corps-ember#1082]
# Problem

When refreshing tasks page on a project no other users show up.

No JS console errors.

Looking at the Ember Inspector and all needed data seems to be available.

![tasks_ _code_corps_by_code_corps_ _code_corps](https://cloud.githubusercontent.com/assets/12616684/23187359/7eb68e62-f858-11e6-864f-f04b7953b958.png)

**Comment by begedin** [comment]
I can reproduce this easily and I'm working on a fix.
