### ISSUE TITLE
Bug: Unassignment of tasks no longer works

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1090]
# Problem

I'm not sure when it happened exactly, but as far as I can tell, tasks can no longer be unassigned.

There is no difference between rendering an assigned or unassigned user in the dropdown and clicking on an assigned user calls the same method to re-assign as it would clicking some other user entirely.

**Comment by JoshSmith** [comment]
Is this being handled by a PR or unaddressed?

**Comment by begedin** [comment]
Being handled by #1091
