### ISSUE TITLE
Do not redirect the user when loading terms of service or privacy policy pages

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1094]
# Problem

Our onboarding flow right now redirects you from any route to the onboarding routes if you're in an onboarding state. This means that a user cannot access the terms of service or privacy policy when in this flow.

We should find a way to prevent these pages from ever redirecting on transition.

**Comment by begedin** [comment]
Our current flow, to be more precise is

- on each transition, check if current user is onboarded
- if not onboarded AND we are not transitioning to a route that is part of onboarding THEN transition to onboarding

# Solution

Change the above decision flow to

- if not onboarded AND not transitioning to an onboarding route AND not transitioning to tos/privacy routes THEN transition to onboarding

This whole thing is happening in 

https://github.com/code-corps/code-corps-ember/blob/develop/app/routes/application.js#L226

- [ ] Add list of excluded routes to the process of deciding if user should be redirected to onboarding
- [ ] Add tos and privacy routes to that list
- [ ] Add tests to ensure these routes are excluded from redirection
