### ISSUE TITLE
Create an onboarding header for the donation process

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1095]
# Problem

We need to modify the site header when the user is making a donation as part of signing up:

- The header should hide the left navigation.
- The header should hide the right user menu.
- The header should show the logo and it can be clickable.
- When the user is finished donating, the right navigation of the header should display a button to "Finish signing up"

**Comment by begedin** [comment]
When the user donates, they can move from `signed_up_donating` to `donated`. At that point, the header can show the `finish signing up`, which would transition the user from `signed_up_donating` to `donated`, correct? 

Or would it be slightly different? The transition to `donated` happens immediately on donation. The `finish signing up` nagivates to profile editing (to set first and last name) and then continues with the normal onboarding flow.

Either way, that part needs some clearing up, but is relatively simple.

The more complicated part is the following scenario:

- User tries to donate
- They sign up and sign in, session redirects them back to donate page
- They don't do anything from here. Maybe they kill their browser or something and sign back in later. Maybe they even change their mind about donating. 

How to put them back into the regular sign up flow? Should the header have something like "I changed my mind, let me just continue with the regular sign up process"?.

I would suggest

**Comment by JoshSmith** [comment]
I think it might be overkill to do this in the short-term, so I'm punting and closing this issue.

**Comment by JoshSmith** [comment]
Reopening because we would like to do this, but it is definitely going to take some work. The problem right now is that we have no sense of a user `state` that's "signed up and donated to project", just "signed up and donating to project". This hobbles any possibility of making this work.

**Comment by begedin** [comment]
From my other comments, I do agree with the header. Combined with less strict navigation enforcing if the signup/onboarding is not done yet, it would do some good. 

Adding another state should not be difficult, but it sounds like the state would be about the same as "signed_up", so, for the sake of discussion, any thoughts on simply renaming that state to `ready_for_onboarding` or something along the lines.

**Comment by JoshSmith** [comment]
Done now.
