### ISSUE TITLE
Hide the footer when donating

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1096]
# Problem

When a user is making a donation, the footer should be hidden from the UI to allow focus for the other elements on the page. This should likely be handled via a service.

**Comment by begedin** [comment]
Is the footer hidden, or is it simply a different footer? 

Is the appearance of the footer dependant on the route we're on, or on the user state? If it's a matter of having different footers on the `project.donate` and `project.thank-you` routes, then a service is overkill. We simply change the template layouts of those routes.

**Comment by JoshSmith** [comment]
Closing this because I think it's not really necessary actually.
