### ISSUE TITLE
Donation thank you page shows "finish signing up" button if you just signed up

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1097]
# Problem

When donating and just signing up for the first time, the thank you page should have a button that navigates you to the rest of the onboarding process. You should not be able to navigate elsewhere except to finish onboarding.

**Comment by begedin** [comment]
This seems to overlap with #1095. Should the "finish signing up" be present in both places, or just one of them?

Also, what is the user state then the "finish signing up" button is supposed to be visible. Is it still `signed_up_donating`, or is it `donated`

Lastly, what does "navigates you to the rest of the sign up process" mean. 
- Does it simply take the user to the first onboarding route (where they set their name)?
- Does it transition the user state and let the auto-redirect infrastructure we have handle the navigation?

**Comment by JoshSmith** [comment]
It should be present in both places.

The state should be `signed_up_donated`.
