### ISSUE TITLE
Page layout broken in firefox & edge

### ISSUE THREAD

**Issue by olegko** [code-corps/code-corps-ember#1113]
# Problem

https://www.codecorps.org/code-corps/code-corps loads broken in firefox & edge. The entire page (minus header) drops down below the fold. 

Likely a css/html issue.

## Subtasks
- [ ] Fix layout in Firefox
- [ ] Fix layout in Edge

## References

https://drive.google.com/file/d/0B72MVEjaD3RrUWEyTzlmN2d0aUE/view?usp=drivesdk

**Comment by JoshSmith** [comment]
![](https://lh6.googleusercontent.com/LdYaKDLERlPsYfK4YTSkzPP5sJ5z1Sq3RBkGBVT3zD_tz0tvqHBULc-Io5sYAOvpf721crI6Z46cwSo=w2018-h1412-rw)

**Comment by olegko** [comment]
Likely issue: .container {height:100%} [Thanks to @chjpugh]

Removing that line fixes issue in FF & Edge and doesn't negatively affect Chrome

**Comment by JoshSmith** [comment]
Can we see if that affects other parts of the app, e.g. tasks?

**Comment by olegko** [comment]
Confirmed that it doesn't affect tasks or new tasks screens

**Comment by chjpugh** [comment]
Guys made a codepen trying to duplicate the issue: http://codepen.io/chjpugh/pen/XMXgVb

Basically I think the issue is that the containers are children of a flex item.  They are inheriting their parent's height in ff. Digging through forums but this seems like a firefox bug.

**Comment by JoshSmith** [comment]
@chjpugh do you have anywhere to link to that mentions this being a Firefox bug by chance?

**Comment by JoshSmith** [comment]
Also this is a really good minimal test case here.

**Comment by chjpugh** [comment]
This seems to cover it: http://stackoverflow.com/a/35537510
I found something a bit clearer yesterday, but of course, no luck now.

**Comment by chjpugh** [comment]
It's debateable if it is a bug. Both Chrome and FF/IE just interpret the height spec differently.  

**FF/IE** consider the flex height of the flex item as the set height.  So when you have a child (like we do with .container) at 100%, they take on the flex height of their parent. 

**Chrome** doesn't consider the flex-height so there is no set height for the flex item and thus the children are set at auto.  

We probably need to refactor the HTML so these are not container items (at least from what I can tell from the SASS files Container is meant to be a higher-level wrapping div, not really nested inside a flex box (but maybe not?). Alternatively, we could add some specific css to set all containers within flex boxes to height:auto.
