### ISSUE TITLE
Builds sometimes start failing for no reason. "Rebuild without cache" fixes them.

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#112]
I'm not sure what's going on, but it started happening to me locally first.

Runin `ember t` would cause phantomjs to crash after the 7th or 8th test module (not sure which at the moment). Deleting `node_modules` and rerunning `npm install` fixes it locally. Pushing to the remote then causes `Circle CI` to fail for the same reason, so a `Rebuild without cache` is needed. After that, everything starts working again.

**Comment by begedin** [comment]
After a bunch of digging, #119 seems to fix this, but I'll wait for a merge and revisit later to double check.

**Comment by JoshSmith** [comment]
@begedin is this fixed? I haven't seen it.

**Comment by JoshSmith** [comment]
@begedin bump.

**Comment by begedin** [comment]
@JoshSmith Last I checked, the problem was us using PhantomJS 2.0 +. I believe we're down to 1.9.something, so it should be good now.

**Comment by JoshSmith** [comment]
Closing then.
