### ISSUE TITLE
Discussion: Should we maintain and render a list of user organizations?

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1121]
# Problem

Before the switch from `organization-membership` to `project-user` records, we displayed a list of the user's organizations on their profile page.

Now that the switch is being made, this goes away and is being replaced by a list of their projects.

However, technically, implicitly, a user still has many organzations. We just don't explicitly define this relationship:

```Javascript
// models/organization.js
owner: belongsTo('user', { async: true })
```

Technically, we could define a `hasMany` inverse on the user model:

```Javascript
// models/user.js
organizations: hasMany('organization', { async: true, inverse: 'owner' })
```

We could then render that list somewhere. It would give a user easy access to organizations they own. This is a long way in the future, though, so I'm not sure it's needed. On the other hand, it would be relatively simple to implement.

**Comment by JoshSmith** [comment]
This seems pretty low priority to me right now, so going to keep it open but mark it as such.

**Comment by JoshSmith** [comment]
We have a user projects now, and I don't think having a user organizations is worth doing relative to that.
