### ISSUE TITLE
New task submit button doesn't turn blue when fields are populated

### ISSUE THREAD

**Issue by daveconnis** [code-corps/code-corps-ember#1128]
Most greyed out button in the Code Corps UI are locked until the required field is filled in. When the required field is given, the button "releases" and turns blue. 

Right now, the task button is grey through the whole process as well as clickable. When submitting a task for the support docs, I thought I hadn't unlocked the button and filled out every field imaginable waiting for the button to turn blue.

**Comment by JoshSmith** [comment]
Yep, is legit bug. 🐛

**Comment by JoshSmith** [comment]
In `task-new-form` we just need the `input` to add a class of `default`.

**Comment by JoshSmith** [comment]
This should actually be done in a recent PR.
