### ISSUE TITLE
Add a "Submit Project" button that links to our Typeform

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1152]
# Problem

We removed the container that linked out to Typeform, but have no method for letting people know how to submit a project. We should absolutely try to do this.

**Comment by juan-sierra** [comment]
# In progress:

This looks OK but is a bit intrusive so I talked to @JoshSmith and he suggested to get rid of it and add it as an item on the header.

<img width="1568" alt="screen shot 2017-04-04 at 10 06 31 pm" src="https://cloud.githubusercontent.com/assets/8007671/24983878/0893b7b4-1fb8-11e7-9b03-e785755695b6.png">

So now we have this:

<img width="1680" alt="screen shot 2017-04-12 at 7 38 25 pm" src="https://cloud.githubusercontent.com/assets/8007671/24983889/13e987b0-1fb8-11e7-9f8f-c982b0a97cce.png">

**Comment by JoshSmith** [comment]
Closed by #1256.
