### ISSUE TITLE
Fix styles for skills-typeahead when placed into task sidebar

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1171]
# Problem

The `skills-typeahead` component inherits a min-width which makes it overflow from the task sidebar UI. This is visible in `project/tasks/task/new.hbs`, for example. 

The style should be fixed to deal with this issue, but in a way that does not negatively impact the look of the component in other places it's used in, for example, the project settings page, templates/start/skills, etc.

## Subtasks
- [ ] Fix style for `project/settings/tasks/task/new` and `project/settings/tasks/task/task`
- [ ] Make sure style in `project/settings/profile` and `/start/skills` is still good

**Comment by JoshSmith** [comment]
@chjpugh did you say this was already completed?

**Comment by chjpugh** [comment]
@JoshSmith It seemed to be fixed to me, but maybe @begedin can confirm.
