### ISSUE TITLE
Extract the task assignment UI from the task card into a component

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1172]
# Problem

Right now, `task-card.hbs` has the following code: 

```hbs
  {{#if canAssign}}
    {{#power-select
      beforeOptionsComponent=(component "power-select/before-options" selectRemoteController=selectRemoteController)
      buildSelection=(action "buildSelection")
      class="select-inline"
      disabled=userSelectDisabled
      dropdownClass="select-inline-dropdown"
      loadingMessage=""
      matchTriggerWidth=false
      onchange=(action "changeUser")
      options=userOptions
      placeholderComponent=(component "task-card/user/unselected-item" click=(action "stopClickPropagation") task=task)
      registerAPI=(action (mut selectRemoteController))
      search=(action "searchUsers")
      selected=selectedOption
      selectedItemComponent=(component "task-card/user/selected-item" click=(action "stopClickPropagation"))
      tagName="div"
      as |user select|
    }}
      {{select-inline-dropdown/list-item
        iconUrl=user.photoThumbUrl
        lastSearchedText=select.lastSearchedText
        primaryText=user.username
        secondaryText=user.name
      }}
    {{/power-select}}
  {{else if taskUser}}
    {{task-card/user/selected-item select=(hash selected = selectedOption)}}
  {{/if}}
```

We need to extract this into a component, to make it reusable in other parts of the App.

## What the component should look like:

The way I see it, the only thing we require from the "public interface" from the component is

```hbs
{{user-assignment task=task onSelect=onSelect}}
```

To elaborate 
- we assign the task to render user assignment for.
- we assign the action to call when the user makes a selection from the dropdown

**Internally**, the component

- Figures out the currently assigned user, renders it
- Figures out if the currently signed in user is able to assign/reassign, rneders if/else parts of the above template code based on that. It should probably use an `ember-can` ability for that.
- Calls assigned action when a user makes a selection from the dropdown list.

At a glance, not much will be needed here. Most of it is already implemented and it's just a matter of moving it into the component. The key is to test it properly.

## Subtasks
- [ ] extract into component according to specs
- [ ] write tests for component

**Comment by JoshSmith** [comment]
Closed by #1434
