### ISSUE TITLE
Simplify project card button logic

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1176]
# Problem

As a followup to #1170:

The two base cases are:

- There is a membership
- There is no membership

For the first one, show a `membership-status` component with 3 states

- loading
- request sent (role eq pending)
- member (role eq something else)

For the second one, we just use the current component.

```hbs
{{#if session.isAuthenticated}}
  {{#if currentMembership}}
    {{membership-status membership=currentMembership}}
  {{else}}
    {{project-join-modal onJoin=(action onJoin project) project=project skills=projectSkills}}
  {{/if}}
{{else}}
  {{link-to "Join project" "signup" class="button default small"}}
{{/if}}
```

Potentially rename this to `project-user-status` to move away from `membership`.

**Comment by begedin** [comment]
@JoshSmith I did not realize you've created an issue, so I made a duplicate #1181 

The other one has more information, so I'm closing this one.
