### ISSUE TITLE
Markdown areas do not style <ul> and <li> tags as lists

### ISSUE THREAD

**Issue by sasjkia** [code-corps/code-corps-ember#1180]
When using standard list html code for ordered and unordered lists, no bullets are rendered

Issue occurs when updating project description:
![image](https://cloud.githubusercontent.com/assets/19363959/24183054/0cd0b430-0e9c-11e7-9db8-0289509e4bc3.png)

**Comment by JoshSmith** [comment]
Our styling for `ul` and `li` does not allow for these markdownable areas to accept these styles right now.

We should ideally have some set of styles that are applicable to all these areas.

Thanks for the report!
