### ISSUE TITLE
Add ability to join a project

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#12]
You should be able to click a button in a project to join it. We should flash success (and maybe some sort of popover to really drive home the thanks and give some orientation), and change the button.

**Comment by begedin** [comment]
@JoshSmith Are we still joining a project here?

We only have organization memberships now, as far as I can tell. How would the UI work now?

**Comment by JoshSmith** [comment]
@begedin not really joining a project, no. I'd like @jimmynotjim's thoughts on the UI. I was thinking we should have a means to "join the team" from the project, which goes to joining the organization and awaits approval.

**Comment by JoshSmith** [comment]
I had a long conversation with @jimmynotjim about this last night. Maybe he can update you here? I think he's going to have some new wireframes ready for this soon.
