### ISSUE TITLE
Add ember-web-app

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1211]
# Problem

We can get some of the benefits of native app feel on mobile browsers by adding https://github.com/san650/ember-web-app

**Comment by jderr-mx** [comment]
@JoshSmith Adding https://github.com/mike-north/ember-add-to-homescreen might go well with this too. Do we have some assets for creating icons and a splash screen?

**Comment by JoshSmith** [comment]
Yes we do! Let me know what kind of assets you're thinking about. What kind of splash screen might there be?

**Comment by jderr-mx** [comment]
Just need some icons/logos, I can see about getting the splash screen working and then turn it over to the more visually talented :)

**Comment by JoshSmith** [comment]
Do you have Sketch? If not you can just tell me what sizes you need and I can provide those.

**Comment by jderr-mx** [comment]
I do not have sketch, doing a little research now on sizing.

**Comment by jderr-mx** [comment]
So here is what I was able to figure out:
icons, 192x192 (Android) 180x180 (Apple) 120x120 (Apple)
Launch Screen 750x1334px

**Comment by jderr-mx** [comment]
Looks like launch screen no longer works for iOS. Android has this option from Chrome 47 on

> In Chrome 47 and later, a splash screen is displayed for a web application launched from a home screen. This splashscreen is auto-generated using properties in the web app manifest, specifically: name, background_color, and the icon in the icons array that is closest to 128dpi for the device.

**Comment by JoshSmith** [comment]
@jderr-mx do you have things you still need from me on this? I'm guessing so, but playing catch-up now.

**Comment by jderr-mx** [comment]
I'll need icons at some point, I have some placeholder ones to mock in. I'm
not blocked, I still need to test splash screen on Android too. Whenever
you get to it I'm good

**Comment by JoshSmith** [comment]
@jderr-mx would you mind creating an issue for me to give you those and assigning it to me? Then I'll get on top of it.
