### ISSUE TITLE
Discuss: Consider switching to pods for code organization.

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#126]
In short, we have a lot of components now and it's getting difficult to navigate through the project. I believe a pod structure would make sense here, so I'd like us to discuss the possibility of switching to that..

**Comment by JoshSmith** [comment]
Seems reasonable to do. It might be best to do once some of these larger PRs are merged. Too many irons in the fire right now.

**Comment by JoshSmith** [comment]
I think that maybe we want to punt on this until this RFC is resolved: https://github.com/emberjs/rfcs/pull/143

It looks like there will be a migrator.

**Comment by JoshSmith** [comment]
Closing in favor of #156.
