### ISSUE TITLE
Enable github auth feature by adding button to profile route

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1267]
# Problem

Once all other tasks in this milestone are done, we should enable the connect feature by adding the link button in #1263 to the user profile route.

## Subtasks
- [ ] Add `github-connect-link-button` from #1263 to profile page
- [ ] Add profile page acceptance test checking that the button renders and has the proper href. 

## References

Blocked by #1266

**Comment by JoshSmith** [comment]
I would think this would be done in settings, actually. What do you think?

**Comment by JoshSmith** [comment]
We might want a settings submenu and put that into an integrations tab or something.

**Comment by JoshSmith** [comment]
For example:

https://d3vv6lp55qjaqc.cloudfront.net/items/011L0n2i3B1c271g2O0u/Screen%20Shot%202017-05-31%20at%2010.35.56%20PM.png?X-CloudApp-Visitor-Id=1336043&v=09cbffb5

**Comment by begedin** [comment]
Anything works, really, as long as it's somewhere.
