### ISSUE TITLE
Fix post previewing

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#129]
The way we're handling post previewing doesn't actually allow the post type or title to be set, which means that the type gets reset on pulling data down from the server. All we want to avoid is generating comment notifications and publishing a post, not altogether avoiding other data being set.

**Comment by begedin** [comment]
I'm not sure I completely follow here.

The `post-title` component actually displays a property that is completely separate from the record. The user can edit that property as they see fit and then, when they click "save", the value of the property is set to the post title and the post record is saved.

if we are just generating the preview, then yes, upon a server response, post title will be reset, but we're still displaying the separate `newTitle` property. I guess we need the same behavior for `postType`?

I'll see about implementing that.
