### ISSUE TITLE
Minor Signup Page UX Improvements

### ISSUE THREAD

**Issue by LennonR** [code-corps/code-corps-ember#1323]
# Problem

Based on placement on the other side of the divider, the let's go button doesn't seem to be associated with the name form and is confusing.  

Proposed Improvement:

![signuppage](https://cloud.githubusercontent.com/assets/916139/26764904/8f45bc3a-493e-11e7-9779-e1e1ed520ce9.jpg)

**Comment by JoshSmith** [comment]
@LennonR this is merged and should be shipped soon, pending some other changes.

**Comment by JoshSmith** [comment]
🙌  to both you and @ilovethebends. Fun to see an issue get raised and fixed without me even realizing what's happening. 😂
