### ISSUE TITLE
New Ember module import syntax.

### ISSUE THREAD

**Issue by snewcomer** [code-corps/code-corps-ember#1380]
# Problem

Ember is moving towards importing just the modules you need instead of the global `Ember` import.

https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md

## Subtasks
- [ ] use https://github.com/ember-cli/ember-modules-codemod to replace `import Ember from 'ember'` with `import Component from '@ember/component'`.
- [ ] some situations will not be covered by this codemod.  Need to evaluate on an individual basis.

Might need to plan on when this can be best accomplished given other PR's in the pipeline.

**Comment by JoshSmith** [comment]
Fortunately there are not terribly many outstanding PRs, but it will indeed take some time/effort to replace everything we need to replace, particularly if tooling isn't quite able to cut it.

**Comment by WenInCode** [comment]
I really like this one, but mostly because I am excited about the new syntax and I was looking at the code mod earlier today.

**Comment by snewcomer** [comment]
I can tackle today if you would like @JoshSmith
