### ISSUE TITLE
Handle display of empty body in tasks/comments with "No description provided.

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1385]
# Problem

It's possible for both `Task` and `Comment` to now have a `null` body. We should handle this in the various components by doing an `if` check in the hbs template and rendering: 

> _No description provided._

Just like that, in italics.

**Comment by fxvarga** [comment]
Found an additional issue while looking into this.

Should we handle empty inputs in the submittable-textarea component, or will those get turned to null in server?

- Currently if the body textarea is not clicked into before save, ```'<p>undefined</p>'``` is sent to server.
- If the body textarea is clicked into but left empty then ```'<p></p>'``` is sent to the server.

**Comment by JoshSmith** [comment]
@fxvarga Good call! I think it's perhaps worth opening a separate issue for this.

While we allow `NULL` values in the database it's really only due to GitHub allowing these values to be null.

I'd like to explore running client-side validations on this and not allowing anything to even be submitted without there being a value. The reason for this is general contributor experience. A task without a description is not very helpful. A comment without one is even less so. In both of these cases it should really have a client-side presence validation.

We've discussed adding in changeset validations in #609. This would be an ideal first case to introduce it, no?

**Comment by begedin** [comment]
My general opinion is that client side validations are welcome and greatly enhance the client, but server side validations are still needed, generally speaking.

The specific example above, though, is a client-side bug and should absolutely be resolved. We should not be sending '<p>undefined</p>'. I'd even consider it a `submittable-textarea` bug, not something to do with validations specifically.

**Comment by JoshSmith** [comment]
Closed by #1407
