### ISSUE TITLE
Change Install on GitHub button link

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-ember#1396]
# Problem

It should link to the app at `/installations/new`, otherwise the flow is confusing.

You would see this:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/071w020R0Z3p2b2G0v1u/Screen%20Shot%202017-09-27%20at%2011.15.53%20PM.png?X-CloudApp-Visitor-Id=1336043&v=14976910)

But prefer this:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/2a0y2c1G1x2k2F1l2G24/Screen%20Shot%202017-09-27%20at%2011.16.34%20PM.png?X-CloudApp-Visitor-Id=1336043&v=33ae831a)

**Comment by daveconnis** [comment]
This issue should be closed, I think.

**Comment by begedin** [comment]
I believe so to, albeit it ended up being implemented in a different way.

Instead of the link being specified in the component directly, we specify the app root link in the environment, then compute the install link in the component.
