### ISSUE TITLE
Bug when clicking assign a task and clicking out of it

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1443]
# Problem

- Open the console
- Click to assign a task
- Dismiss the form
- Type any string
- You should get the following error:

```
Assertion Failed: {{power-select}} If you want the default filtering to work on options that are not plain strings, you need to provide `searchField`
```

**Comment by WenInCode** [comment]
I have reproduced this locally, and am looking into it. I'll update here if I have any questions

**Comment by WenInCode** [comment]
I'm having a hard time wrapping my head around how the `selectRemoteController` is being set in https://github.com/code-corps/code-corps-ember/blob/develop/app/templates/components/task-card.hbs#L33

Where is it being referenced? Looking in the debugger, it looks like it is https://github.com/cibernox/ember-power-select/blob/6b1e472d394a9322f9a25a668cf0686bbeb2ad2c/addon/components/power-select.js#L225-L234
but I am not certain

Looking in the debugger it looks like we are returning from [get(this, 'selectRemoteController').actions.close(e);](https://github.com/code-corps/code-corps-ember/blob/develop/app/components/power-select/before-task-options.js#L9) before we expect to which might be why the filter is still around.

Anyway, if you know where the `selectRemoteController` is coming from it might help me debug this issue :)

**Comment by JoshSmith** [comment]
@WenInCode perhaps this will help https://github.com/cibernox/ember-power-select/issues/549#issuecomment-227229404
