### ISSUE TITLE
Get status of GithubRepo syncing by polling

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1468]
# Problem

We need to evaluate which is faster vs better to do and then do that:

Using the component created in #1466:

- poll for sync status of ProjectGithubRepo
- or, get sync status through Phoenix channel

If the latter, we probably need to create some blocking issues here and in the API.

Blocked by #1466

**Comment by begedin** [comment]
Polling would involve no API work at all, since we already presumably have a  `GithubRepo`/`ProjectGithubRepo`. 

We could use an `ember-concurrency` Task which periodically makes a request to reload each the github repo model.

```Javascript
pollServerForChanges: task(function * () {
  while (true) {
    yield timeout(1000);  // wait 1 second
    get(this, 'githubRepo').reload();
  }
}).on('didInsertElement').cancelOn('willDestroy').restartable(),
```

That's the basic implementation.  I'd say, past that, we need

- 30 minutes to  implement a way to stop polling once the status is final (probably by changing the `true` condition to something specific
- 90 minutes to figure how how to write a proper test for this, one that would not wait around for a second in order to fully execute

**Comment by begedin** [comment]
Channels would be more complex, but also more feature complete. Sadly there would be little overlap between the two solutions.

We would have to

**Implement a channel API-side which can be instructed to notify the client when a record changes** ~ 4-6 hours 
- need to research, implement basic channel, testing infrastructure, but would pave the way for great things

**Extend our adapter for `githubRepo` to connect to this channel and push json data it receives through it into our store (to update records)** 
- there's https://github.com/BlakeWilliams/ember-phoenix-adapter, but it hasn't been updated in 3 years.
- https://github.com/foxnewsnetwork/ember-phoenix-chan is a tad better, but also 1-2 years old. 
- We should look at those and figure out our own approach. Probably start with just the `githubRepo` adapter, then figure out a generalised solution ~ 4-6 hours
- https://github.com/phoenixframework/phoenix/issues/286 also has some info

This should cause the record to refresh automatically and the UI to re-render with a status change.

- As added polish, we should probably add a css transition so the change is more apparent to the user ~1 hour

**Comment by begedin** [comment]
@JoshSmith My estimates for this one are

~ 2 hours for the quick. I wouldn't say dirty, since it's a proper solution. It's just that it's specific to this case and doesn't pave the way for anything
~ 1.5 to possibly 2 days for the "proper" channel solution

**Comment by JoshSmith** [comment]
We'll go with the quicker version for now then.

**Comment by snewcomer** [comment]
@JoshSmith is this something you want me to help with?

**Comment by JoshSmith** [comment]
@snewcomer sure! I think it might be blocked by #1467 though, which I'm likely to work on tomorrow depending on status of API things.
