### ISSUE TITLE
Design post page

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#15]
We need to design the individual post page.

**Comment by JoshSmith** [comment]
@jimmynotjim this is also probably on the next highest priorities.

**Comment by jimmynotjim** [comment]
Added to the Wireframes, under Standard Desktop, third row, second through fourth columns

**Comment by JoshSmith** [comment]
Created end state for posts:

![post - created](https://cloud.githubusercontent.com/assets/321667/15060832/5e26d0cc-12e3-11e6-92db-255d44042be7.png)

**Comment by JoshSmith** [comment]
Editing a comment in a post:

![post - comment editing](https://cloud.githubusercontent.com/assets/321667/15060848/76309dec-12e3-11e6-8c9a-e3391ed4efe8.png)

**Comment by JoshSmith** [comment]
Posted comment in a post:

![post - comment posted](https://cloud.githubusercontent.com/assets/321667/15060852/7f1dfd1e-12e3-11e6-9a2c-e5cebf4b7b40.png)

**Comment by JoshSmith** [comment]
I am not sure how far off this is from completed work. Needs follow-up.

**Comment by JoshSmith** [comment]
This is implemented in code now.
