### ISSUE TITLE
Organization Invites

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1541]
This Task task should serve as a starting point for the Organization invites milestone

# General requirements

- [x] admin sends invite to organization by email
- [x] organization owner receives email, clicks invite link (link has a token)
- this takes them to [www.codecorps.org/organizations/new](https://www.codecorps.org/organizations/new) - #1542, #1543
  - might be a root route such as [www.codecorps.org?organization-invite=<token>](https://www.codecorps.org?organization-invite=<token>) which redirects to above route
  - owner fills out `name`, `icon`, `description`- page should probably clarify this is still creating a project, not an organization
 - once created, owner is redirected to [www.codecorps.org/org-slug/projects/new](https://www.codecorps.org/org-slug/projects/new)
  - preferably, the icon is prefilled from organization, any other applicable fields may be as well
  - they fill out the rest of the information and click create
  - not sure where they are taken next, really. should we have a "Project created" landing page of some sort?

**Comment by joshsmith** [comment]
Closing in favor of other more specific issues.
