### ISSUE TITLE
Add /org-slug/projects/new

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1544]
We need a route where an organization owner can create a new project.

- add route
- authorization checks if user is owner of organization
- `model` hook inits the project
- we should check that it's possible to redirect to this route by providing a pre-built project model. If I'm not mistaken, this ought to skip the `model` hook
- route is basic, just renders the form with `title`, `description`, `long_description_markdown`,  `website`
- successful save redirects to `/org-slug/project-slug/`
- failed save renders errors
- required acceptance tests
  - requires authentication
  - requires user to be organization owner
  - successful save
  - failed save

# Questions

Presumably, the initially sent invite is intended to allow for one project.

My guess is, we want to use the `approved` field on the project so admins have to explicitly approve each new project. Is the initially created project auto-approved, or is it still required to be explicitly approved by an admin? Either way, that would probably be done on the side of the API, so we should open an issue to discuss.

From the model on the API side, I assume `title`, `description` are required, the rest is not, but maybe it ought to be?

# Estimate

~2 hours

**Comment by snewcomer** [comment]
I can hop on this!

**Comment by joshsmith** [comment]
This page should allow the user set (in order):

- Icon (required)
- Title (required)
- Description (required)
- Website (optional)
- Categories (required)
- Skills (required)

The user can submit and get errors if anything is missing. If they try to leave the page, they should get a native confirm dialog that warns them they'll lose all their information.

We should be able to save local copies of all the above and chain the creation of the categories/skills.

It might also be possible on the API side to actually create the categories/skills all at once, but for a first go the categories/skills happening after the fact would be fine, too.

**Comment by joshsmith** [comment]
We'll need to change redirection from organizations page to this page.
