### ISSUE TITLE
Add confirm dialog to archive action on the task show page

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-ember#1551]
# Problem

On the task show page, we want to add a confirm dialog to the archive action. When clicking archive, you'll get a native modal that says:

> Are you sure you want to archive this task? Archiving this task will remove it from your **#{task_list_title}** task list.

This will need to modify the `archive-task` component to add:

- The modal dialog request, using `window.confirm`
- Get the title of the task list
- Determine the action based on the outcome of the modal dialog answer

You'll need to test this in an integration test.

There should be examples of `sinon.stub(window, 'confirm').callsFake()` out there for this, possibly not in an integration test, though.

**Comment by snewcomer** [comment]
@joshsmith ok for me to tackle this?

**Comment by joshsmith** [comment]
Yeah absolutely.
