### ISSUE TITLE
Consider extracting out check buttons into an async check button component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#162]
Should DRY up some similarities between `category-item` and `role-item`.

**Comment by idelairre** [comment]
I see two ways of doing this:

1. a generic "item" component that you configure by passsing attributes to the template or
2. a base component that will be extended by category-item or role-item respectively

With my current knowledge of Ember 2 seems more feasible. 1 is preferable to me, I'm just not sure how to generically handle computed properties that rely on services.

**Comment by JoshSmith** [comment]
I haven't given a lot of thought to this yet but definitely think there's a good way to extract it out in a way that's DDAU.
