### ISSUE TITLE
Scroll to bottom after new conversation part loaded if scrolled to bottom

### ISSUE THREAD

**Issue by joshsmith** [code-corps/code-corps-ember#1637]
# Problem

If a new conversation part is loaded in the background due to a websocket update _and_ you're already scrolled to the bottom, we should scroll to the bottom of the conversation thread again to keep the messages view fully scrolled for you.

**Comment by joshsmith** [comment]
@snewcomer did you want to mark as `in progress`?

**Comment by snewcomer** [comment]
@joshsmith yeah I can do it now!

**Comment by snewcomer** [comment]
@joshsmith It looks like there is a scrollBottom method already?  https://github.com/code-corps/code-corps-ember/blob/develop/app/components/conversations/conversation-thread.js

**Comment by joshsmith** [comment]
There is, but we need to make it work under the conditions above, as well.

**Comment by snewcomer** [comment]
@joshsmith How do you reliably test the creation of conversation parts?  I tried running with `development` with the elixir backend, but seems to be sorting the conversations so I'm thinking I'm not running this with the right setup.

**Comment by joshsmith** [comment]
@snewcomer I'm not sure I do anything special. I'm just messaging myself from the project and then in another browser I'm in my user's conversations.

**Comment by begedin** [comment]
@snewcomer You can also use an incognite crome tab in place of the second browser
