### ISSUE TITLE
Add ability to close or reopen a post

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#213]
To the left of the comment button should be a "Close post" button when open, and an "Reopen post" button when closed. It should be of the `clear` button style. You can only close or open a post if you're the user who created the post, or you're at least an admin on the project.

**Comment by begedin** [comment]
Working on this one, but don't have a PR yet. Should have it tomorrow morning early.

**Comment by JoshSmith** [comment]
@begedin can you push something up even if it's broken?
