### ISSUE TITLE
Add YUIDoc documentation across the app

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#223]
This is a relatively big project but can be tackled in small parts. Would accept pull requests for any number of small pieces, even as low as a single function being documented would be super helpful.

**Comment by JoshSmith** [comment]
@WenInCode can we add a list here of what all has been doc'ed and what hasn't, or a reference to Inch or something? Would be good to make it easier to know where to jump yet, or maybe create some separate issues for the remaining pieces.

**Comment by WenInCode** [comment]
@JoshSmith Sure I'll add  a list of things that are left.

**Comment by WenInCode** [comment]
# List of files to be documented
## Abilities
- [ ] organization.js
- [ ] post.js

## Adapters
- [ ] application.js
- [ ] comment.js
- [ ] post.js
- [ ] project.js
- [ ] slugged-route.js
- [ ] user.js

## Authenticators
- [ ] oauth2.js

## Authorizers
- [ ] oauth2.js

## Components
- [ ] categories-list.js
- [ ] category-item.js
- [ ] code-theme-selector.js
- [ ] comment-item.js
- [ ] create-comment-form.js
- [ ] demo-categories.js
- [ ] demo-category-item.js
- [ ] demo-posts.js
- [ ] demo-projects.js
- [ ] demo-skills.js
- [ ] drag-zone.js
- [ ] editor-with-preview.js
- [ ] error-formatter.js
- [ ] error-wrapper.js
- [ ] flash-messages.js
- [ ] image-drop.js
- [ ] landing-subsection.js
- [ ] login-form.js
- [ ] member-list-item.js
- [ ] navigation-menu.js
- [ ] organization-header.js
- [ ] organization-member.js
- [ ] organization-profile.js
- [ ] organization-settings-form.js
- [ ] organization-settings-menu.js
- [ ] organization-settings.js
- [ ] pager-control.js
- [x] post-comment-list.js
- [x] post-details.js
- [x] post-filter-dropdown.js
- [x] post-filter-type.js
- [x] post-header.js
- [x] post-item.js
- [x] post-new-form.js
- [x] post-status-button.js
- [x] post-status.js
- [x] post-title.js
- [ ] progress-bar-container.js
- [x] progress-bar.js
- [ ] project-card-members.js
- [ ] project-card-skills.js
- [ ] project-card.js
- [ ] project-categories-list.js
- [ ] project-category-item.js
- [ ] project-container.js
- [ ] project-details.js
- [ ] project-item.js
- [ ] project-list.js
- [ ] project-long-description.js
- [ ] project-menu.js
- [ ] project-post-list.js
- [ ] project-settings-form.js
- [ ] project-settings-menu.js 
- [ ] role-item.js
- [ ] scroll-top.js
- [ ] select-dropdown.js
- [ ] select-option.js
- [ ] signup-email-input.js
- [ ] signup-form.js
- [ ] signup-password-input.js
- [ ] signup-username-input.js
- [ ] site-footer.js
- [ ] skill-button
- [ ] skill-list-item.js
- [ ] slugged-route-model-details.js
- [ ] submittable-textarea.js
- [ ] team-member.js
- [ ] user-details.js
- [ ] user-dropdown.js
- [x] user-menu.js
- [ ] user-organizations-list.js
- [ ] user-settings-form.js
- [ ] user-sidebar.js 
- [ ] user-skills-input-item.js
- [ ] user-skills-input.js

## Controllers
- [ ] project/posts/index.js
- [ ] start/expertise.js
- [ ] start/hello.js
- [ ] start/interests.js
- [ ] start/skills.js
- [ ] application.js
- [ ] index.js

## Helpers
- [ ] capitalize.js
- [ ] end-with-period.js
- [ ] highlight-substring.js

## Mixins
- [ ] can-animate.js
- [ ] onboarding-controller.js
- [ ] onboarding-route.js

## Models
- [ ] category.js
- [ ] comment-user-mention.js
- [ ] comment.js
- [ ] organization-membership.js
- [ ] organization.js
- [ ] owner.js
- [ ] post-user-mention.js
- [ ] post.js
- [ ] preview-user-mention.js
- [ ] preview.js
- [ ] project-category.js
- [ ] project-skill.js
- [ ] role.js
- [ ] skill.js
- [ ] slugged-route.js
- [ ] user-category.js
- [ ] user-role.js
- [ ] user-skill.js
- [ ] user.js

## Routes
- [ ] organizations/slugged-route/settings.js
- [ ] organizations/slugged-route.js
- [ ] project/posts/index.js
- [ ] project/posts/new.js
- [ ] project/posts/post.js
- [ ] project/settings/contributors.js
- [ ] project/posts.js
- [ ] project/settings.js
- [ ] start/expertise.js
- [ ] start/hello.js
- [ ] start/interests.js
- [ ] start/skills.js
- [ ] about.js
- [ ] application.js
- [ ] index.js
- [ ] login.js
- [ ] project.js
- [ ] project-list.js
- [ ] projects.js
- [ ] settings.js
- [ ] signup.js
- [ ] slugged-route.js
- [ ] start.js
- [ ] team.js

## Serializers
- [ ] application.js
- [ ] post.js

## Services
- [ ] ajax.js
- [ ] background.js
- [ ] code-them.js
- [ ] credentials.js
- [ ] current-user.js
- [ ] drag-state.js
- [ ] mention-fetcher.js
- [ ] navigation-menu.js
- [ ] onboarding.js
- [ ] raven.js
- [ ] session.js
- [ ] user-categories.js
- [ ] user-roles.js
- [ ] user-skills.js

## Transforms
- [ ] array.js

## Utils
- [ ] mention-parser.js
