### ISSUE TITLE
"post type" text cut off when making new post

### ISSUE THREAD

**Issue by ethantanner** [code-corps/code-corps-ember#233]
When creating a new post the post type dropdown text is cut off. See attached screenshot
![image](https://cloud.githubusercontent.com/assets/6895721/16221042/35c27004-3756-11e6-9226-a7bd30260dcb.png)

Found on Chrome 51.0.2704.103 on Windows 10

**Comment by JoshSmith** [comment]
Screw cross-compatibility! Buy a Mac and download Chrome or something! Get off my lawn!

**Comment by JoshSmith** [comment]
Question is whether we should really be overriding the dropdown, or if there's a better non-terrible way to do this. Will accept any PR that makes CSS less terrible.
