### ISSUE TITLE
Error: The adapter rejected the commit because it was invalid

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#238]
https://app.getsentry.com/code-corps/code-corps-ember-staging/issues/135694641/

```
Error: The adapter rejected the commit because it was invalid
  at EmberError (bower_components/ember/ember.debug.js:16581)
  at ParentErrorClass (ember-data/adapters/errors.js:23)
  at o/r (ember-data/adapters/errors.js:49)
  at this (ember-data/adapters/rest.js:811)
  at func (ember-simple-auth/mixins/data-adapter-mixin.js:103)
...
(6 additional frame(s) were not displayed)

Error: The adapter rejected the commit because it was invalid
```

**Comment by olegko** [comment]
firefox, win10

went to create a new account, first step successful. was redirected to the profile page (name, image)
entered name, added an image (btw, does it just resize + center?), clicked on "continue" (or whatever the button is) and nothing happened. tried clicking a few times, nada

refreshed the page and was redirected to the "choose your interests" page

**Comment by JoshSmith** [comment]
Closing in favor of new errors that come in.
