### ISSUE TITLE
Add email suggestions to signup form

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#246]
We can use this https://github.com/mailcheck/mailcheck

**Comment by JoshSmith** [comment]
Hey @M0nica just checking to see if you need any help on this.

**Comment by begedin** [comment]
Note that we have https://github.com/johnotander/ember-mailcheck as a wrapper to use mailcheck with.

**Comment by M0nica** [comment]
I am still interested in helping with this but may need some help.
