### ISSUE TITLE
All members of a project are displayed on the project

### ISSUE THREAD

**Issue by ethantanner** [code-corps/code-corps-ember#281]
![image](https://cloud.githubusercontent.com/assets/6895721/16360869/66cd8fc6-3b3e-11e6-9d73-edcced1773ea.png)
There needs to be a limit, if there were 1000 members then 1000 photos would be shown.

**Comment by begedin** [comment]
What do we go with here? Just pick the first x and add something like "..." to the end for now? A great option would be to sort by contribution amount, but I'm not really sure how to measure that.

We could sort by role.

**Comment by JoshSmith** [comment]
For now I think we just pick six or seven of them and add a "+# more".

**Comment by ethantanner** [comment]
Transferred issue to codecorps! https://www.codecorps.org/code-corps/code-corps/posts/8
