### ISSUE TITLE
Sign Up test -staging

### ISSUE THREAD

**Issue by joproducts** [code-corps/code-corps-ember#282]
codeCorp Sign up test - 6/26/16 @jamesodonnell
Sev - low
WIN7/MAC OS -  Chrome 51.0.2704; FireFox 46.0.1
	1.http://www.pbqrpbecf.org/
	2.select 'Sign Up' link
DEBUG: -------------------------------
DEBUG: Ember             : 2.6.0
DEBUG: Ember Data        : 2.6.0
DEBUG: jQuery            : 2.2.4
DEBUG: Ember Simple Auth : 1.1.0
DEBUG: -------------------------------
Error in event handler for (unknown): TypeError: Cannot read property 'disable' of undefined
Failed to parse SourceMap: https://d3onq9263d8on4.cloudfront.net/assets/vendor.map
Error in event handler for (unknown): TypeError: Cannot read property 'disable' of undefined

extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'disable' of undefinedhandler @ extensions::uncaught_exception_handler:8(anonymous function) @ extensions::uncaught_exception_handler:100EventImpl.dispatch_ @ extensions::event_bindings:377EventImpl.dispatch @ extensions::event_bindings:394target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:151dispatchOnMessage @ extensions::messaging:336
Failed to parse SourceMap: https://d3onq9263d8on4.cloudfront.net/assets/vendor.map
	3. Enter username, email address, password
	4. Select Sign Up context button
	5. Select a photo to upload
	6. enter a name.
	7. Select the Let's go! context button.
==In each test the same error occurred only when selecting the Sign Up link in the upper right hand corner

**Comment by JoshSmith** [comment]
I think this has been resolved.
