### ISSUE TITLE
Handle errors better

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#29]
For API error wrapping, some research notes:

Ember-Data expects the typical JSON API error format, but there is a difference in how it works with validation, and other errors.
- If the response code is 422 Unprocessable entity, ember data will initialize a [`DS.InvalidError`](http://emberjs.com/api/data/classes/DS.InvalidError.html).
- For any other code, the initialized error will be [`DS.AdapterError`](http://emberjs.com/api/data/classes/DS.AdapterError.html)
## `DS.InvalidError`

`DS.InvalidError` expects the error data to be in the following format (the listed properties are the minimum it needs to have):

``` JavaScript
{
  errors: [
  {
    detail: "Detailed message"
    source: { pointer: "data/attributes/dasherized-field-name" }
  }
  ...
  ]
}

```

If the errors are in this format, ember-data's serialization layer will parse them and the model will have its `model.errors` property set. Note that the `model.isError` will not be set to true in this case. The `model.isError` property is only set to true if, during a `model.save`, the server **returns an error that is not a validation error**.

The default field name format is dasherized, but my guess is, if we override our serializer to expect underscored property names by default, that setting will also apply to errors.

My proposal is that, for validation errors, we do a PR on the API side which changes how we serialize those errors so the format is valid for ember.

Then, we handle such errors by catching a failed save on the model. We will have access to properties such as `model.get('errors.username');` and it will be easy to display them.

Fetching the property in the way I describe will give us back an object:

``` JavaScript
[
   {
      "attribute": "username",
      "message": "The username is too long"
    }
]
```

Basically, `detail` is mapped to `message` and `pointer` is mapped (with modification) to `attribute`.
## `DS.AdapterError`

This instance is used for any other error, including model save errors that aren't validation errors. This type of error expects the format:

``` JavaScript
errors = [
  {
    title: 'Adapter Error',
    detail: message
  }
]

```

If the API doesn't return a body with an error response, a default error object will be generated, with a single error in it, with `detail` set to `'Adapter operation failed'`.

There are two additional error classes which are sometimes used - `DS.AbortError` and `DS.TimeoutError`. They inherit from `DS.AdapterError` by initializing it with custom messages of their own.

Basically, I don't really think we should handle errors in any custom way.  Ember-data already wraps errors on it's own well enough.

At most, we might want to override the messages ember uses, so we could do a wrapper for that, which checks the error type and returns a different message based on that.

Something like

``` JavaScript

function overrideErrorMessage(error)
  if error.typeOf(TimeoutError) { 
    error.set('message', 'Our custom message for timeout error');
  } else if (error.typeOf(AbortError) {
    error.set('message', 'Our custom message for abort error');
  }
}

```

We would likely override the above two, since as far as I can tell, they are raised when the operation fails, but the server doesn't respond with anything.

For an `AdapterError`, the server did respond with something, so we should leave the message the server provided.

**Comment by begedin** [comment]
I looked into this some more.

Sadly, while ember-data has different classes defined for each error type, there doesn't seem to be a simple, non-hacky way  of determining the error type from the catched save request on a record.

I'm imagining handling it in the following way:

* We modify our adapter by hooking into the error system. `DS.InvalidError` is left alone, while other types of errors are parsed and then sent to an error handling service, which works like a sort of queue.
*There is a global-level component which access the error handling service and displays a pop-up somewhere, showing the error information. 
* Once the pop-up is dismissed, or goes away after a while, or however we wish to implement it, the error is considered "consumed" and popped out of the service.
