### ISSUE TITLE
Rename project-grid-item to project-card

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#293]
This is a minor change. We should rename the `project-grid-item` component to `project-card`, and see if there are any higher-level components we should name change to reflect this.

**Comment by thomascchen** [comment]
Do we also want to rename components like `project-grid-item-skills-list` and `project-grid-item-members-list` to `project-card-skills-list` and `project-card-members-list`? And related styles and class names and such for consistency?

**Comment by JoshSmith** [comment]
@thomascchen yes, absolutely. I would actually suggest we rename the following:

- `project-grid-item-skills-list` => `project-card-skills`
- `project-grid-item-members-list` => `project-card-members`

What do you think?

**Comment by thomascchen** [comment]
@JoshSmith sounds good! 👍

**Comment by JoshSmith** [comment]
@thomascchen did you want to take this one?

**Comment by JoshSmith** [comment]
If so, you can self-assign.

**Comment by thomascchen** [comment]
Yup, I'm on it!
