### ISSUE TITLE
Change to dasherized attributes and relationships to reflect API changes

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#305]
We need to remove both for `keyForAttribute` and `keyForRelationship` in both `app/serializers/application` and `mirage/serializers/application` to reflect changes in the API, once merged.

**Comment by JoshSmith** [comment]
Blocked by https://github.com/code-corps/code-corps-api/issues/391.

**Comment by begedin** [comment]
Note that we might need to do some mirage serializer changes for this as well.

**Comment by JoshSmith** [comment]
Will be done in #363.
