### ISSUE TITLE
Add Forking Docs

### ISSUE THREAD

**Issue by noslouch** [code-corps/code-corps-ember#326]
One part of the CodeCorps missions seems to be breaking down barriers to entry for people trying to get into open source development. We've got [pretty](https://github.com/code-corps/code-corps-ember/blob/develop/CONTRIBUTING.md) [good](https://github.com/code-corps/code-corps-ember/blob/develop/docs/SQUASHING.md) for open source first-timers, but nothing on the details of maintaining a fork. 

Let's add a little write up for volunteers who aren't explicitly part of the project that covers
- [ ] Adding `code-corps-ember` as a new remote
- [ ] Knowing when to to do a hard reset or rebase when your fork goes stale
- [x] Maybe a more detailed breakdown on what rebase does?

**Comment by hkasera** [comment]
@noslouch @JoshSmith Can I take this up? If yes, do you some specific format in mind or just the content as you mentioned above?

Thanks!

**Comment by JoshSmith** [comment]
@hkasera absolutely, feel free to go for it! I'm up for anything at this point and would be happy to see it in either the `SQUASHING.md` or somewhere similar.

And welcome, by the way! 👋

**Comment by JoshSmith** [comment]
@hkasera you might actually want to consider taking on another task first, to not make the merge so difficult when we inevitable want to pull this back into the API repo.

Let me find the issue number. One moment.

**Comment by JoshSmith** [comment]
Tackling #482 first will help make this dramatically easier. Did you want to give that a go and then circle back to this?

**Comment by JoshSmith** [comment]
And feel free to join us in our Slack if you need more help: http://slack.codecorps.org/

**Comment by hkasera** [comment]
@JoshSmith Sure I can try that first 👍

**Comment by JoshSmith** [comment]
@hkasera @rileytaylor ended up tackling #482 but you can definitely come back to this now. Will be a lot easier with the updates.

**Comment by JoshSmith** [comment]
@rileytaylor was this done implicitly with other docs or no?

**Comment by rileytaylor** [comment]
@JoshSmith Partially. We don't talk about manually adding a remote or about hard resets. Those seem like good candidates for `helpful-docs`, what do you think?

**Comment by JoshSmith** [comment]
@rileytaylor sure but I would link to GitHub documentation where it makes sense. It seems duplicative to go too much into things that other people have written about better.
