### ISSUE TITLE
Separate edit permission logic into component mixin

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-ember#335]
While I was working on the docs for the `post-` components I realized that there was some duplication going on around creating/editing posts/titles. More specifically around editing permissions and ownership of posts. I found similar logic in both the `post-title` & `post-details` components.

I think it would be a good idea to refactor these components and separate that logic into a component mixin that can be shared with any current & future components that are concerned with permissions around editing posts/titles/etc.

**Comment by WenInCode** [comment]
I have started working on this, still needs some work, but I will put up a PR soon™

**Comment by JoshSmith** [comment]
@WenInCode were you still working on this?
