### ISSUE TITLE
Determine a new deploy path for Ember

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#375]
Right now we're deploying to Redis, which is very tied up with our existing Rails API.

We're removing Redis as a single point of failure and would like to figure out the best deployment option.

Some considerations:

- We want the deployment in development to match production as closely as possible
- We would still like to use `ember-cli-deploy` if possible, because their pipeline is the gold standard
- We should look to what other deployments look like where Phoenix serves as the API backend
- We have existing infrastructure on AWS with S3 and CloudFront
- We also have some minimal infrastructure with CloudFlare

**Comment by green-arrow** [comment]
So I've done this a couple different ways in the past:

* Deploy `index.html` out to S3 with all of the other assets, and just serve that up from a normal root domain (codecorps.org)
* Deploy `index.html` out to a standalone EC2 instance and serve with NGINX

Something I haven't done before:

* Deploy `index.html` out to our phoenix server in a set directory and let the Elixir app serve the file

**Comment by JoshSmith** [comment]
@green-arrow do you like the S3 approach okay? Have you done this with `ember-cli-deploy`? I'd like to have revision hash capabilities. Downside is that we don't get to experience the deploy in dev, but that may be okay.

**Comment by green-arrow** [comment]
@JoshSmith - Yeah the S3 approach was ok. The main one I used was the EC2 instance with nginx. Both of those are supported by ember-cli-deploy, which is what I used. The S3 approach actually has an official plugin: https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index

**Comment by JoshSmith** [comment]
We should go with the S3 approach for now.
