### ISSUE TITLE
Add templates for issues and pull requests

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/code-corps-ember#389]
To standardize/organize our issues and pull requests, it would be a good idea to have some templates set up.

**Comment by WenInCode** [comment]
I like this idea. At work I use the following template for reference.

```
# what's in this PR?

## why was this created?
## changes that were made
## reasons for decisions
# before
# after
# References
```

I tried this on my phone... And I'm pretty sure I changed the wording a bit but that's around what we use.

**Comment by rileytaylor** [comment]
I'll add those to what I've been brainstorming! 

I'll make a pull with what I've put together this evening so that we can all discuss specifics and argue semantics 😎
