### ISSUE TITLE
Expertise choice format is misleading

### ISSUE THREAD

**Issue by HeroicEric** [code-corps/code-corps-ember#399]
![screen shot 2016-08-26 at 11 32 50 am](https://cloud.githubusercontent.com/assets/602204/18016453/55485fb0-6b81-11e6-8443-d7a1d23758d9.png)

Aligning these choices to the center like this makes it seem like the choices are hierarchical. For example, in the screenshot above, it looks like "Data Science" is a child of "Backend Development".

Possible fixes:
- Make the width of the choices the same
- Don't align them to the center

**Comment by begedin** [comment]
I see the point. @JoshSmith, what do you think?

Maybe making the bounding boxes all equal width, while the text/checkbox inside them is still centered would do the trick?

**Comment by JoshSmith** [comment]
I do see the point, too, though haven't had any complaints so far from the 200 or so people who have signed up.

I had tried left aligned but wasn't totally comfortable with how it looked. Wouldn't mind seeing that again. Would be interested to see how similar widths with center-aligned text inside them looks.
