### ISSUE TITLE
User should be able to navigate to a list of applicable projects from their skills page

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#43]
See #6 

A user selects skills they have and should then be able to click "Show me the projects" to get a list of projects that require the skills they have. 

This navigates from the skills page to the project page, so it is blocked both by #7 and #9 

It will involve either adding a list of skill ids to the projects request, or a user_id as well as changes api-side which would return a list of projects appropriate for the specified user.

@JoshSmith What do you think the better approach would be.

The way I see it, filtering by skills would allow us to later implement a skill-based search of projects, while just fetching projects appropriate for the user would make it a simpler request. Are we planning such project searches in the future?

**Comment by JoshSmith** [comment]
Removing because we will address this in another approach. Low priority.
