### ISSUE TITLE
Add photo to user profile

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#44]
* It should be viewed
* It should be editable
* The API will accept base_64_photo_data, so there is no need to upload. It should suffice to read the photo on the client side and send the bae64 data - blocked by code-corps/code-corps-api#187
* Might be a good idea to limit file size.

**Comment by begedin** [comment]
Blocked by code-corps/code-corps-api#187

**Comment by begedin** [comment]
Blocked by #33

**Comment by JoshSmith** [comment]
This is handled in #109.
