### ISSUE TITLE
Add listing of user's skills to user profile

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#46]
A user should have their skills listed on their profile.

We'll want to use the `{{related-skills}}` component for this, and pass in the `userSkills` of the user who's currently viewing the profile (to see the skills they have in common).

This will need an `h2` or `h3` tag in the component for `Skills`, and perhaps an `( i )` icon that will say "Skills you share are highlighted" when hovering, in a tooltip.

**Comment by JoshSmith** [comment]
I'm guessing this is not still blocked?

**Comment by JoshSmith** [comment]
Nevermind, I see it's not.
