### ISSUE TITLE
Add analytics tracking code sitewide

### ISSUE THREAD

**Issue by olegko** [code-corps/code-corps-ember#460]
# Problem
We need to track our website visitor activity

## Subtasks
- [ ] Please add analytics tracking code immediately after the <body> tag sitewide:
`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-84629400-1', 'auto');
  ga('send', 'pageview');
</script>`

**Comment by JoshSmith** [comment]
@olegko I think this is already being tracked in GA. We're doing it through Segment.

**Comment by olegko** [comment]
ah k. could you add me to the account (analytics def, segment if possible)? - i'll message you the email to add.

along the same lines, have you set the site up in google search console and bing webmaster tools? if not, i'll provide the meta tags to implement.

**Comment by JoshSmith** [comment]
@olegko I don't believe so on latter. Will add you re: first point.

**Comment by olegko** [comment]
Here is the code to add to verify for Google Search Console:
`<meta name="google-site-verification" content="XPIWd8oFDFpXKQC7BHTjyx5f5x7d9ls-AhFCXE7xVes" />`

**Comment by JoshSmith** [comment]
@olegko wouldn’t I have already done this with DNS? Pretty sure there's a record there for the site verification for when we set up Apps.

**Comment by olegko** [comment]
If you wanna go that route, Add the TXT record below to the DNS configuration for codecorps.org.
`google-site-verification=XPIWd8oFDFpXKQC7BHTjyx5f5x7d9ls-AhFCXE7xVes`

**Comment by olegko** [comment]
Alternatively, you can verify the property from the account you used to set up the DNS by going to https://www.google.com/webmasters/verification/home?hl=en, clicking "Add Site" and entering.... https://www.codecorps.org (important that is done this exact way)

Then you can add volunteers@ as a manager - https://support.google.com/webmasters/answer/2453966?hl=en

**Comment by JoshSmith** [comment]
@olegko is this closed now? I think you've been added and the original issue title is no longer relevant.

**Comment by olegko** [comment]
analytics + webmaster tools code confirmed. all good here.
