### ISSUE TITLE
Deleting `node_modules` followed by `npm install` makes some tests fail

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#465]
# Problem

As described in the title, deleting the node modules folder, followed by a reinstall makes some tests fail. My guess is, caching meant some of the addons didn't update. I would love it if someone would be able to reproduce.

**Comment by WenInCode** [comment]
I can try this out in a bit, though I *don't think I have seen it before*. Normally when I remove my `node_modules` I also run `npm cache clear`.

**Comment by JoshSmith** [comment]
Recommend using `nombom` https://www.npmjs.com/package/nombom
