### ISSUE TITLE
Component for donation project logo, title, and description header

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#476]
# Problem

We need to have a reusable component on donation pages for project logo, title, and description as seen in https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191332630 and https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191332621
## Subtasks
- [ ] Add logo
- [ ] Add title
- [ ] Add description
## References

Progress on: #475

**Comment by sbatson5** [comment]
Do we have a sprite for just the Code Corps logo? In the sprite sheet, we seem to only have the logo + the name. Can we get just the Code Corps symbol?

<img width="183" alt="screen shot 2016-10-13 at 3 05 39 pm" src="https://cloud.githubusercontent.com/assets/881981/19362942/85dd1b84-9156-11e6-8b92-066d4c203661.png">

**Comment by JoshSmith** [comment]
@sbatson5 what do you need this for here?

**Comment by JoshSmith** [comment]
Ah, I see the misunderstanding on that design. That is supposed to be the project's logo, name, description, not ours. We're the project in that case.

**Comment by sbatson5** [comment]
Oh. Haha. That makes more sense!
