### ISSUE TITLE
Create reset password screen

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#5]
We need to have a screen to actually reset your password with the new password (on the tokenized URL).

**Comment by jimmynotjim** [comment]
Added to the Wireframes, under `Standard Desktop`, first row, fifth column

**Comment by begedin** [comment]
@JoshSmith Can we paste a screenshot of the UI here? I'm not sure where the wireframes are anymore and that way, someone might be able to create some sort of UI.

**Comment by JoshSmith** [comment]
![reset password](https://cloud.githubusercontent.com/assets/321667/24517839/a3fd8876-1534-11e7-90c1-375db8859145.png)

**Comment by snewcomer** [comment]
@begedin @JoshSmith so is this password reset screen in the user profile section?  Seems like the above would be for forgot password?

**Comment by JoshSmith** [comment]
I think the idea is that you're not necessarily going to be authenticated when resetting it if you had forgotten it.

**Comment by begedin** [comment]
@snewcomer @JoshSmith I did not take a good glance at this, but the screenshot is misleading.

The button should say "Send me a password reset email" or something along the lines. There would be a link to this page from the login page. @snewcomer As you said, this would be "forgot password"

Then the email we send to the user would be a link to a completely separate "reset password" page, where there would be a form with a password, a password confirmation and a submit button with "Save password".

**Comment by JoshSmith** [comment]
Yes I missed that the button text here was completely incorrect.
