### ISSUE TITLE
Pagination is broken

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#506]
# Problem

Pagination is broken when you're on the last page and the pages are <= `totalPages`.
## Subtasks
- [ ] Write a failing test
- [ ] Make the test pass
## References

The code as it should be:

``` javascript
  bounds: Ember.computed('centerPage', 'pagesToShow', 'totalPages', function () {
    let pagesToShow = this.get('pagesToShow');
    let totalPages = this.get('totalPages');

    if (totalPages < pagesToShow) {
      return {
        lower: 1,
        upper: totalPages
      };
    } else if(this.get('onLastPage')) {
      let currentPage = this.get('currentPage');

      return {
        lower: currentPage - (pagesToShow - 1),
        upper: currentPage
      }
    } else {
      let centerPage = this.get('centerPage');
      let range = Math.floor(pagesToShow / 2);
      let pagesToShowIsEven = pagesToShow % 2 === 0;

      return {
        lower: centerPage - range,
        upper: centerPage + (pagesToShowIsEven ? range - 1 : range)
      };
    }
  }),
```

**Comment by laveshaparker** [comment]
Going to take a look at this now since it's labeled `S`.

**Comment by laveshaparker** [comment]
Going to see/do what's left here!

**Comment by laveshaparker** [comment]
Hi @JoshSmith what do you mean by
> and the pages are <= `totalPages`.

?

Also! I'm trying to view this in the app so I better understand this particular scenario, and I'm checking out the project's tasks page per your comment [here](https://github.com/code-corps/code-corps-ember/pull/578#issuecomment-252406899), but I'm not seeing it (gif/screenshot included). Any guidance would be much appreciated!

![no_paginator](https://cloud.githubusercontent.com/assets/5737949/21339844/5c958cbe-c650-11e6-8d88-935383a8a6d3.gif)

**Comment by JoshSmith** [comment]
@laveshaparker there is no more pagination on this page. We're keeping the component around because there will eventually be pagination on other things, but this page does not have it.

**Comment by JoshSmith** [comment]
I think it's `pagesToShow <= totalPages`.

**Comment by laveshaparker** [comment]
Great! Thank you!
