### ISSUE TITLE
Handle "" correctly in /settings/profile

### ISSUE THREAD

**Issue by scarfdestroyer** [code-corps/code-corps-ember#51]
Currently in /settings/profile if a user removes their name/website etc. from the the text box and then clicks update it will erase their previous data.

Not sure what we should be checking for/doing here. For example, we probably want them to be able to remove a website they no longer have access to or user but probably we probably want them to have a name once they add one. 
This or at least ask, "Are you sure you want to remove your Name?" if they previously had information and then are setting it to an empty string.

**Comment by JoshSmith** [comment]
I think the problem here is less removal of data and more treatment of `""` as different from `nil`.

**Comment by JoshSmith** [comment]
Not relevant here. Will be closed by https://github.com/code-corps/code-corps-api/issues/292.
