### ISSUE TITLE
Refactor Projects tests to use page-objects

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-ember#516]
# Problem
Refactor `Projects` tests to leverage [page-objects](http://ember-cli-page-object.js.org/docs/v1.4.x/components). 

## Subtasks
- [ ] Create page-objects
- [ ] Refactor `Projects` tests to use page-objects

## References
- Progress on: #141
- [Contributing Guidelines](https://github.com/code-corps/code-corps-ember/blob/develop/.github/CONTRIBUTING.md)
- Join our [Slack](https://codecorps.slack.com)

**Comment by JoshSmith** [comment]
I'll take this, too.
