### ISSUE TITLE
Write unit tests for the Task model

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-ember#521]
Update unit tests for the `Task` Model. These have already been started, but could use more coverage. We should be testing relationship declarations & computed properties (see [testing guide](https://guides.emberjs.com/v2.8.0/testing/testing-models/))

## References
- Progress on: #98 
- [Model testing guide](https://guides.emberjs.com/v2.8.0/testing/testing-models/)
- [Contributing Guidelines](https://github.com/code-corps/code-corps-ember/blob/develop/.github/CONTRIBUTING.md)
- Join our [Slack](https://codecorps.slack.com)

**Comment by QzSG** [comment]
@WenInCode By `Post` model you do mean the renamed `Task` model?
I see that there is already a `task-test.js` at `tests/unit/models/task-test.js`

Do you require more tests for task.js? Do you have any specific 'must test' conditions?

**Comment by WenInCode** [comment]
@QzSG good catch - I didn't realize these had already been addressed! It looks like you are right. I hadn't realized Posts had already been moved to tests and that the tests for the model were written too! Thanks a bunch, I need to update some more issues to use `Tasks` instead of `Posts`.

**Comment by WenInCode** [comment]
@QzSG on second thought these could use some basic tests around relationship declarations. The computed property seems to already be getting tested. 

Just curious, did you happen to find the project through hacktoberfest? Feel free to drop by our [slack](https://codecorps.slack.com/) and say hello
