### ISSUE TITLE
Write unit tests for the Organization model

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#526]
Write unit tests for the [`Organization` Model](https://github.com/code-corps/code-corps-ember/blob/develop/app/models/organization.js). There is an [existing unit test file](https://github.com/code-corps/code-corps-ember/blob/develop/tests/unit/models/organization-test.js), but it could use more coverage (computed properties & relationship declarations). 

## References
- Progress on: #98 
- [Model testing guide](https://guides.emberjs.com/v2.8.0/testing/testing-models/)
- [Contributing Guidelines](https://github.com/code-corps/code-corps-ember/blob/develop/.github/CONTRIBUTING.md)
- Join our [Slack](https://codecorps.slack.com)

**Comment by idelairre** [comment]
I'm working on this and should have a pull request later tonight.
