### ISSUE TITLE
Write unit tests for the Skill model

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#531]
Write unit tests for the [`Skill` Model](https://github.com/code-corps/code-corps-ember/blob/develop/app/models/skill.js). There is an [existing unit test file](https://github.com/code-corps/code-corps-ember/blob/develop/tests/unit/models/skill-test.js), but it could use more coverage (computed properties & relationship declarations). 

## References
- Progress on: #98 
- [Model testing guide](https://guides.emberjs.com/v2.8.0/testing/testing-models/)
- [Contributing Guidelines](https://github.com/code-corps/code-corps-ember/blob/develop/.github/CONTRIBUTING.md)
- Join our [Slack](https://codecorps.slack.com)

**Comment by WenInCode** [comment]
@JoshSmith I don't think this test actually needs to be updated. There no relationships or computed properties on the [Skill](https://github.com/code-corps/code-corps-ember/blob/develop/app/models/skill.js) model.

**Comment by kumarmj** [comment]
I am doing this, pull request coming soon thanks!
