### ISSUE TITLE
Write unit tests for the User model

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#536]
Write unit tests for the [`User` Model](https://github.com/code-corps/code-corps-ember/blob/develop/app/models/user.js). There is an [existing unit test file](https://github.com/code-corps/code-corps-ember/blob/develop/tests/unit/models/user-test.js), but it could use more coverage (computed properties & relationship declarations). 

## References
- Progress on: #98 
- [Model testing guide](https://guides.emberjs.com/v2.8.0/testing/testing-models/)
- [Contributing Guidelines](https://github.com/code-corps/code-corps-ember/blob/develop/.github/CONTRIBUTING.md)
- Join our [Slack](https://codecorps.slack.com)

**Comment by kumarmj** [comment]
I found this issue to be good for me as newbie, I would be working on it. thanks
