### ISSUE TITLE
Add preview model unit test to ensure all attributes (body, markdown) are accounted for.

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#552]
# Problem

I've detailed the "problem" in https://github.com/code-corps/code-corps-ember/pull/547#issuecomment-250958697 but to outline it...

Having a single test, per model, that simply checks all attributes are accounted for, makes sense. We basically look at the model test in ember in the same way as the view test in phoenix.

An example of such a test is https://github.com/filipecrosk/code-corps-ember/blob/2197e7926fa6f3b1d30eee63a3705623e2a15f18/tests/unit/models/project-test.js#L17

On one hand, we could look at this as "requiring the contributor to add a new attribute to the model twice", but really, we should look at a test like that as a fail-safe to make sure the contributor hasn't accidentally removed a model attribute. Sort of a "you did this, are you sure?".

It would make sense to add a test that ensures all attributes are accounted for.

We've already merged #543 without doing this, so this issue is to cover that.

## Subtasks
- [ ] Add test to ensure preview model has `body` and `markdown` attributes

## References
- Progress on: #98 
- [Model testing guide](https://guides.emberjs.com/v2.8.0/testing/testing-models/)
- [Contributing Guidelines](https://github.com/code-corps/code-corps-ember/blob/develop/.github/CONTRIBUTING.md)
- Join our [Slack](https://codecorps.slack.com)

**Comment by kumarmj** [comment]
Just submitted pull request, I am working on this.
