### ISSUE TITLE
Write helper for asserting model attributes

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-ember#554]
# Problem
Model tests for checking attributes are pretty repetitive. To Dry it up we should write a helper for asserting attributes. Ex. `assert.hasAttribute(attributes, 'attribute');`

## References
- [Original Comment](https://github.com/code-corps/code-corps-ember/pull/546#discussion_r81476237)

**Comment by JoshSmith** [comment]
@filipecrosk you're working on this now, right?

**Comment by filipecrosk** [comment]
@JoshSmith yes
