### ISSUE TITLE
Make yuidoc generation stop removing all other files in /docs

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-ember#558]
# Problem
There are a lot of important guides under the `/docs` folder. It is also where the yuidoc documentation is generated. The current problem with that is that each time yuidoc generation happens, every other file under `/docs` is removed. We need to find a way to either configure yuidoc to stop removing the other files or have the yuidoc documentation get generated in a different folder (preferably a subfolder, under `/docs`). It's also important to make sure that you can still serve and view the docs in the browser after the changes.

## References
- [Original Comment](https://github.com/code-corps/code-corps-ember/pull/556#issuecomment-251026653)
- [Yuidoc site](http://yui.github.io/yuidoc/)

**Comment by rileytaylor** [comment]
From a glance I don't see any options to pass that will prevent items from being deleted. Seems that some of their examples output to YUIDoc specific folders, likely for this reason.

**Comment by JoshSmith** [comment]
Maybe `/docs/yuidoc`?

**Comment by rileytaylor** [comment]
That would seem most logical, I will make it so. :vulcan_salute:
