### ISSUE TITLE
Broken email validation?

### ISSUE THREAD

**Issue by sarupbanskota** [code-corps/code-corps-ember#592]
# Problem

I was trying to sign up and discovered that the email validation has something wrong.

I know there is some sort of validation, since I got this screen at first: 
<img width="636" alt="screen shot 2016-10-09 at 5 35 26 pm" src="https://cloud.githubusercontent.com/assets/3149580/19221200/2bd4b3ca-8e47-11e6-812c-ab3dba82e3aa.png">

----------------

But then:
<img width="536" alt="screen shot 2016-10-09 at 5 35 29 pm" src="https://cloud.githubusercontent.com/assets/3149580/19221201/3220b9ae-8e47-11e6-819b-7bb9a8a27c0f.png">

## Subtasks
- [ ] understand how current validation works
- [ ] figure out what needs fixing
- [ ] fix it!

## Notes

I am on Safari 9.1.1

**Comment by JoshSmith** [comment]
@sarupbanskota basically the only remotely valid email regex is `/@/`. There are so many edge cases as to make it to really worth trying anything else, lest you block a legitimate email address.

**Comment by JoshSmith** [comment]
Wondering what you think of reasoning above and whether this is still an issue?

**Comment by sarupbanskota** [comment]
@JoshSmith I agree with your reasoning, but I disagree with it being a non-issue :-)

Most users are going to find it confusing, as it's not normal to see an email with a `.com` or equivalent being marked valid.

**Comment by sbatson5** [comment]
For reference (and a good read): https://davidcel.is/posts/stop-validating-email-addresses-with-regex/

There are so many weird edge cases with email addresses. The logic is that at the end of the day, it is better to send an email to an address that isn't valid versus potentially not sending an email when you should.

**Comment by JoshSmith** [comment]
@sbatson5 we just a had a separate (non-GitHub) conversation where we discussed just that! Thanks for linking for future reference.

I do think the regex could be improved by checking for one character before and after. That still fits _any_ email in the RFC and is a good enough thing.

And agree with your final point. These issues will help there:

- https://github.com/code-corps/code-corps-api/issues/20
- #276 
- #246

**Comment by JoshSmith** [comment]
Closing in favor of above-referenced issues. Let me know if you disagree.
