### ISSUE TITLE
Use Yarn Package Manager

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-ember#602]
[Yarn](https://yarnpkg.com/) - a new package manager that extends npm was just released. It looks like a big improvement over npm. We should give it a shot!
## References
- [Yarn](https://yarnpkg.com/)
- [Yarn's Github](https://github.com/yarnpkg/)

**Comment by sashashakun** [comment]
Hello.
I want to help with this. 
Will return with PR in a day or two. Is it ok?

Thanks.

**Comment by JoshSmith** [comment]
@sashashakun absolutely. Just let us know when you're working on it so we can mark it as in progress. Also, keep in mind that I don't think Yarn is likely to work with GitHub URLs yet, so if anything in our `npm` or `bower` requires that, we'll be blocked until that's done.

**Comment by sashashakun** [comment]
@JoshSmith so I am already starting it means that you can mark it as in progress i think. Also I checked `package.json` and `bower.json` and don't see that anything require github url, but of course some of deps of deps may need it)
