### ISSUE TITLE
Run Ember exam in Circle CI

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/code-corps-ember#603]
# Problem

We can't run ember exam in Circle CI since Circle (intentionally) doesn't load `ember-cli`. `ember-try` should allow us to run ember exam and provides potential future use cases of running the tests with several different configurations (i.e. running with beta ember builds).

## Subtasks
- [x] Add ember-try
- [x] Configure to run ember exam

## References

Progress on: #419

**Comment by JoshSmith** [comment]
@rileytaylor is there a PR associated with the first tick?

**Comment by rileytaylor** [comment]
@joshsmith No, at least not yet. Didn't have a chance to make one before heading to class. It's currently added on branch `603-add-ember-try`. So far all I've done is add it to the package.json, which is mostly what I meant by that tick. Planning on testing/making it do what we want tonight.
