### ISSUE TITLE
Remove nesting for routes

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#61]
Unlike on the API side, routing on the Ember side should be mostly unnested. Nesting routes in Ember means nesting of UI, which is mostly not what we want. An individual post should not be nested inside the list of posts, for example.

**Comment by JoshSmith** [comment]
Blocked by #62.

**Comment by begedin** [comment]
I generally agree with this with the idea, but I think our nesting is a case where it is required due to UI composition.

For example, when we look at a projects posts, editing or adding a new post, we probably still want to see the project details in the header. This would be the parent, project route, while the subroutes are rendered within an outlet.

Looking at this right now, though, project-post-list is part of the project-details component. We should move it outside, and into a `project.posts.index` route.

What I would do is make the `posts`, `new`, `edit` and `post` routes at the same level, so they all render within the parent project's outlet.

My proposal is this:

* rewrite router slightly:

```JavaScript
this.route('project', { path: '/:sluggedRouteSlug/:projectSlug' }, function() {
   this.route('posts')
   this.route('new-post');
   this.route('view-post', { path: '/:number' });
   this.route('edit-post', { path: '/:number/edit' });
});

* move the `project-post-list` outside of `project-details` and render it directly in`/templates/project/posts`
* modify the behavior of `project-post-list` so it adheres better to the `data-down-actions-up` philosophy. When the user does something like changing the page or the filter, this should propagate into the `project.posts` route, where the current page of posts will be reloaded based on new parameters. This is how most of our other components work. I wrote this one earlier in the process, when I didn't quite yet figure out the concept.

So yeah, I completely agree an indivudal post should not be nested in a list of posts, that's an outright bug/design mistake I made. I think we should have nesting, however.

**Comment by JoshSmith** [comment]
I think we've got some confusion about the UI. I think with the proposed route scheme you have, what would we ever see on the project page? Do we want to be hiding posts behind a click when the idea is that we want to get people quickly onboarded to a project? That seems likely to produce headaches.

But if we have the list of posts on the project page itself, we'll lose the convenience of having the project information to display at the top of the page.

It's still not clear to me that we want an embedded, nested UI like this.

**Comment by begedin** [comment]
If we want the list of posts on the project page itself, then we would have two options

1. Keep it where it is
2. Move it to a new route, but make that route the default. It doesn't need to have anything added to the path. Ember already does this basically, with the hidden 'index' subroute. That means that when navigating to the `/:memberSlug/:projectSlug`, ember would first go to the `project` route and fetch the project model, then automatically go to `project.posts` route and fetch the posts. The url would remain `/:memberSlug/:projectSlug`. As far as I know, this is pretty typical ember behavior.

Do you agree with the convenience of having basic project information on the 3 subroutes (view, edit, show post).

If project information is not needed on these pages, then I would agree that we do not need nesting at all here. If we do want project information on those 3 pages, but we want to get it there some other way, then we wouldn't need nesting either, but I'm unsure which approach would follow conventions better. I'm leaning slightly towards nesting in that case.

This likely is confusion about the UI, though, so any basic sketch of how it would look like would probably clear things up for me.

**Comment by JoshSmith** [comment]
I think this was closed.
