### ISSUE TITLE
Make acceptance tests fail properly because of routing issues

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#62]
Right now the acceptance tests do not fail properly. I think that inserting things into the schema directly like we're doing with Mirage right now is causing an issue where we have false positives on acceptance. In reality, we need to ensure that the route is going through the process of hitting a particular API URL, which I don't believe is happening right now.

**Comment by begedin** [comment]
The way I understood mirage, adding things to the schema doesn't mean it get's added to the ember data store, so the mock server is still getting hit first.

What the issue might be:
* Our mock for `GET /:organizationSlug/:projectSlug` serves as a sort of catch-all for many cases, so we get unexpected behavior
* Our adapters might have bugs in how they determine the route for certain queries, so we would likely need to write tests for those.

**Comment by begedin** [comment]
@JoshSmith: Do you have a specific case where you encountered an issue, so I could try and debug it?

I could also add tests to our acceptance modules which simply ensure that, when navigating to a route, a specific API endpoint gets called? That might be simpler and more explicit than adapter unit tests.

**Comment by JoshSmith** [comment]
I think this is fixed by #64. I'll try to find more explicit instances of this in future.
