### ISSUE TITLE
Adding a comment does not add comment in UI

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#66]
When you add a comment to a post, that comment is not reflected in the UI. You have to reload to fetch the new comment data.

**Comment by begedin** [comment]
I believe this was fixed with #63 

The assertion at https://github.com/code-corps/code-corps-ember/blob/develop/tests/acceptance/post-comments-test.js#L76 also ensures that this isn't the case anymore. 

Could anyone double-check on their side and close if that is the case?

**Comment by JoshSmith** [comment]
You're right, closed by #63.
