### ISSUE TITLE
Improve donation process (not MVP for donations)

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#669]
# Problem

Our donation process is mostly done, but there are useful improvements we can add post "release".

- [ ] Use `ember-stripe-service` to generate client-side errors per input field
- [ ] Highlight inputs in red when they have errors
- [ ] Add error information below each input when errors are present
- [ ] _optional_ Credit card highlights as the correct one when entered

## References

Extracted from #668

**Comment by JoshSmith** [comment]
No longer relevant due to using `ember-stripe-elements`.
