### ISSUE TITLE
Implement CSS styling for card-list component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#675]
# Problem

The `card-list` component, although implemented, lacks any kind of styling.

![](https://cl.ly/3B0i0T163j2W/Screen%20Shot%202016-11-12%20at%207.17.38%20PM.png)

## Subtasks
- [x] Add styles to the component, using BEM (as described in #672)

**Comment by rlueder** [comment]
I got this one. 👍
