### ISSUE TITLE
Add "add card" button to the card-list component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#676]
# Problem

The `card-list` component needs an add card button to show the `credit-card` component.

![](https://cl.ly/3B0i0T163j2W/Screen%20Shot%202016-11-12%20at%207.17.38%20PM.png)

## Subtasks
- [ ] Add the add card button
- [ ] Write tests for it

**Comment by rlueder** [comment]
I'm working on this one as well since 675 sets most of the other elements related to it.
