### ISSUE TITLE
Show donation-progress component in the project sidebar

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#679]
# Problem

We implemented the donation-progress component, but it hasn't been placed above the "Donate" button in the project's sidebar.

See: https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191332624

![](https://cl.ly/461t091s3v44/Screen%20Shot%202016-11-13%20at%206.02.59%20PM.png)

## Subtasks
- [ ] Add the donation-progress component into the sidebar
- [ ] Test that it's there

**Comment by alexwilkinson** [comment]
On it!
