### ISSUE TITLE
Discuss: Removal of semicolons on a project-wide basis

### ISSUE THREAD

**Issue by hbrysiewicz** [code-corps/code-corps-ember#70]
There is a segment in the community over whether to use semicolons or not. One might argue that it looks cleaner, or that it encourages developers to better understand the language. I have been semicolon-free since about November and it feels and looks a lot better, especially with the new es2015 shortened syntaxes (fat arrows, spread, etc). 

This would just require a mass purging of semicolons in js files as well as an update to the .jshintrc.

Take that little semicolons.

**Comment by JoshSmith** [comment]
@begedin any thoughts on this?

**Comment by begedin** [comment]
I'm really, really used to semicolons in JavaScript, but I don't have a strong opinion on it. It would be more ruby-like, but I don't see that as an argument for or agains it.

I think my stance on this could be summarized as ```¯\_(ツ)_/¯ ```

**Comment by JoshSmith** [comment]
I think this has been open for awhile and deserves a response, which is simply that I don't know if it's worth the time/effort to put into it. I'm sure codeshift or something could make it trivial to do, but it's just low enough relatively priority that I'm going to opt to close this.

Thanks for the suggestion, regardless!
