### ISSUE TITLE
Build UI for setting donation goal as current?

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#704]
# Problem

There is no UI to set the donation goal as current. We should build one. Something like a "make current" button on the donation goals should do the trick.

**Comment by JoshSmith** [comment]
@begedin sorry, think I was unclear about this. This should be handled by the API, likely when the donation goals are updated _and_ when the cached total donated column changes on the project. We'll need to find the donation goal that is most closely above the current amount and set that to the current goal. That is, it's shifting, and it's dependent upon the other goals and the current monthly raised.

**Comment by JoshSmith** [comment]
Closing in favor of API issue.
