### ISSUE TITLE
Investigate leaving codeship

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#73]
Codeship is great, but makes running tests on forks impossible right now.

We should see if Circle, Travis, or someone else can do this better.

**Comment by hbrysiewicz** [comment]
I have tried both Circle CI and Travis and like the experience with UI and working with support form Circle CI better.

**Comment by JoshSmith** [comment]
Big fan of Circle, too.

Does it support the tests running on forks?

**Comment by hbrysiewicz** [comment]
Yep! https://circleci.com/docs/fork-pr-builds

**Comment by JoshSmith** [comment]
Apparently, yes, with some restrictions. https://circleci.com/docs/fork-pr-builds

Biggest things to think about are ENV variables, which I guess are not enabled in the forks. I wonder what kind of impact that would have for us.

**Comment by hbrysiewicz** [comment]
Nice find, buddy ;P :+1:

**Comment by JoshSmith** [comment]
![](https://media.giphy.com/media/ohdY5OaQmUmVW/giphy.gif)

**Comment by JoshSmith** [comment]
We've already made this transition in API. Need to do so here.

**Comment by JoshSmith** [comment]
Closed by making Circle work. :green_heart:
