### ISSUE TITLE
Don't let users who have a subscription create a new one

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#784]
# Problem

If you go to `http://localhost:4200/code-corps/code-corps/donate?amount=25` manually when you already have a subscription, you would be able to create a new one.

## Subtasks
- [ ] Figure out a better alternative for this (updating it? redirecting?)

**Comment by rlueder** [comment]
I think taking the user to the project’s home should be fine, I can't see why someone would manually enter that, most likely it could be their browser suggesting it in the address bar, or maybe they might have bookmarked it. Either way, if they already subscribed I don't think it would be confusing to be redirected to the project's home.

**Comment by JoshSmith** [comment]
@rlueder we made the URL so it could be shareable, so you could link someone to donate to the project for some amount.

**Comment by rlueder** [comment]
That shouldn't be a problem though right? If a user that has a  subscription lands on that screen we should be able to tell if they have already subscribed after they log in, if yes just send them to project home. If it's a new user (e.g. received a link from someone else) just let them go through and donate.

Another approach: create a page similar to thank you page with a message like "You're already subscribed to this project. What about supporting a different project?" and perhaps highlight a few random projects just below it (similar to headshots on thank you page).

**Comment by JoshSmith** [comment]
@rlueder I _really_ like the idea of the latter approach. And maybe it could have even in the short-term just some links/buttons to share that project to someone else.

**Comment by alexwilkinson** [comment]
I'll look into this. @rlueder @JoshSmith I'll start with a redirect to the project page for simplicity, and then maybe we can think about the new thank you page idea? Just may be a touch ambitious for me given my 0 experience with the project for the moment : )

**Comment by JoshSmith** [comment]
@alexwilkinson sounds perfect to me. Can you open an issue for the new idea, using the latter approach?

**Comment by alexwilkinson** [comment]
@JoshSmith sure thing!

**Comment by JoshSmith** [comment]
To help understand this issue a bit more, understand that a user has many `stripe-connect-subscriptions` but only one for the particular project. They cannot be subscribed to a project more than once.

We do not have a direct relationship between project and subscription, though. That relationship goes through the `stripe-connect-plan`, which itself belongs to a `project`.

There's a `TODO` to consider relating the two together, and this is another indication that that might make sense to do. If it does, then you can open an issue in @code-corps/code-corps-api, but that will likely be fairly involved.

If there's a way to be hacky for now, we might prefer that over a lot of API changes.

**Comment by alexwilkinson** [comment]
Cool, that all makes sense. Thanks for the context! I'll let you know if I could use some more.

**Comment by alexwilkinson** [comment]
This should probably be closed in favor of #798.
