### ISSUE TITLE
"image-drop" class has no default visual styles

### ISSUE THREAD

**Issue by rlueder** [code-corps/code-corps-ember#785]
# Problem

- the clickable area for uploading a photo only shows on hover (image attached), there's no indication that there's something to be clicked when first landing on the page;

## Subtasks
- it'd be a simple update to the styles so that the drop area is visible not only on hover

![upload_picture](https://cloud.githubusercontent.com/assets/341543/20645995/07c15438-b436-11e6-8cb9-505c092ad7f5.png)

**Comment by JoshSmith** [comment]
This has been improved.
