### ISSUE TITLE
Fix rendering of pieces of the credit card page as things slowly load in

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#811]
# Problem

@begedin when I talked about "flashing" of the components here, I meant that if something loads in, then we do not want to show the components loading piecemeal.

Right now, though, if you create your customer/card/etc and that loads slowly, you'll watch as the form changes to load in the card, etc.

It's pretty unexpected and we would prefer to prevent re-rendering the UI until the entire operation completed, not until each atomic promise returns.

Understandably, we may have to render the card or something after an error.

Maybe we need to rethink how this looks in order to make things clearer, but as it stands, things are simply kind of confusing from the user's perspective.

**Comment by WenInCode** [comment]
I'm not sure I entirely understand the explanation here, but my team has built out `wait-for` and `wait-for-render` components in our app that sound like they *could* solve this/or a similar issue. I would have to get a better understanding of the problem though.

**Comment by JoshSmith** [comment]
@WenInCode there is long, complex promise chaining happening here and various components respond to boolean logic around whether a relationship exists. These relationships that return from inside the chained promises can then make rendering change piecemeal.

**Comment by JoshSmith** [comment]
Closed by #821.
