### ISSUE TITLE
Deal with `shouldBackgroundLoadRecords` when the default changes in a future version of ember-data

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#82]
Not sure if we will have to do anything. The way it's implemented right now, it should not affect us, but we might want to make use of it when it does change.

**Comment by JoshSmith** [comment]
This is blocked until `ember-data` changes. Nothing to do here but check every so often.

**Comment by JoshSmith** [comment]
@begedin bump to check if this has changed.

**Comment by JoshSmith** [comment]
Closed in #484.
