### ISSUE TITLE
Refactor the credentials service

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#836]
# Problem

There are a few things I'm not satisfied with in the current implementation, that can maybe go into a separate issue to refactor later now that this is working, in order from smallest to largest refactorings:

- We could maybe stand to rewrite the promise logic and see if we can collapse the API from `membership` and `fetchMembership` into a single API. I'm not sure this is possible given the `ember-can` issue mentioned in #834.
- This service is poorly named. `credentials` does not really make clear what we're doing here, which is checking for organization permissions. Maybe even just `organization-permissions` would be a better name.
- We're acting like this is something akin to the `onboarding` service, which is application-wide, a design decision driven by the idea of a user requesting permissions while being on a project route or organization route. Is the user on the route? Set the current organization in the service. This doesn't reflect other use cases, though, like checking for organization permissions in a list of organizations. Suggest that we consider thinking more functionally here. This would reduce a lot of the magic out of setting the organization implicitly in routes (and elsewhere) and make everything more explicit.
- I'm not entirely positive that the Ember application should even be responsible for any of the complexity here. I would like to consider hiding most of the complex permission logic inside of the user via the JWT. Updates to the user's data would then reflect in organization permissions.

**Comment by JoshSmith** [comment]
This is pretty out of date.

**Comment by JoshSmith** [comment]
@begedin can you let me know if you think this should remain closed or if there's anything we should address elsewhere?

**Comment by begedin** [comment]
Nothing to address, really. I've eliminated all of the code from it. Then, I temporarily added new code, which was moved into the one component using it. That part, I don't like too much, but I've created #1122 to address it, and I don't think it's something urgent.
