### ISSUE TITLE
Consider refactoring usage of session.session.authenticated.user_id with current user object

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#84]
I'm introducing a current user object in #76 that could be used for fetching the user ID instead of digging into `session.session.authenticated.user_id` for it.

We should consider replacing that if it's a viable approach.

**Comment by begedin** [comment]
We can switch to checking current user in projects, but I'm not sure how that will affect tests. Our `authenticateSession` test helper, provided by `ember-simple-auth` accepts the object that gets stored into `session.session` as the second argument.

I guess if the behavior for fetching the current user is still there and is triggered, then it will be fetching automatically, so it should not be an issue, but I'll have to check.

We could also always stub the session in tests, but I think that should be avoided if we could do it cleanly.
