### ISSUE TITLE
Task UI: task-board component

### ISSUE THREAD

**Issue by marineb** [code-corps/code-corps-ember#842]
# Problem

- Holds the four columns
- Never taller than window
- Scrolls left/right to show columns
- Should be hardcoded

## References

Progress on: #841

**Comment by JoshSmith** [comment]
![91a5c6be-bc8f-11e6-99dc-7e3bd4ea7ebf_png__1020x700_](https://cloud.githubusercontent.com/assets/321667/20995030/119050ec-bca9-11e6-8b68-ad20a2a837f4.png)

**Comment by jasierragarcia** [comment]
working on it
