### ISSUE TITLE
Task UI: task-list component

### ISSUE THREAD

**Issue by marineb** [code-corps/code-corps-ember#843]
# Problem

- The column which holds the tasks (tasks are handled by a 3rd component)
- Should be hardcoded

## References
Fixes #862
Progress on: #841

**Comment by JoshSmith** [comment]
![91a5c6be-bc8f-11e6-99dc-7e3bd4ea7ebf_png__1020x700_](https://cloud.githubusercontent.com/assets/321667/20995011/f6f32318-bca8-11e6-92f5-98eb732daf29.png)
