### ISSUE TITLE
Task UI: task-card component

### ISSUE THREAD

**Issue by marineb** [code-corps/code-corps-ember#844]
# Problem

- The task itself
- Should be hardcoded

## References

Progress on: #841

**Comment by JoshSmith** [comment]
![91a5c6be-bc8f-11e6-99dc-7e3bd4ea7ebf_png__1020x700_](https://cloud.githubusercontent.com/assets/321667/20994987/d14fc094-bca8-11e6-8744-c127e2f534dc.png)

**Comment by JoshSmith** [comment]
Tasks only show the `title`, `number`, `type` (renders the top border and the icon), and `inserted-at` date (using the moment helper).
