### ISSUE TITLE
Code Corps using too much memory and CPU in Chrome?

### ISSUE THREAD

**Issue by rlueder** [code-corps/code-corps-ember#845]
# Problem

Code Corps running in Chrome seems to be using a lot of memory and CPU even though I had only a few (5) tabs open.

In Chrome click on 'Window' and select 'Task Manager':

![image](https://cloud.githubusercontent.com/assets/341543/21001571/c22fdeee-bce6-11e6-894d-c966a7834156.png)

## Tech Specs
- MacBook Pro (Retina, 13-inch, Early 2015)
- 2.7 GHz Intel Core i5
- 16 GB 1867 MHz DDR3
- Intel Iris Graphics 6100 1536 MB

**Comment by rlueder** [comment]
I'll try running Chrome with all my extensions disabled just in case it' something external to the website causing the issue, I'll report back.

**Comment by JoshSmith** [comment]
AFAICT right now we're using way less memory now. Could have been an addon or something with prior Ember version.
