### ISSUE TITLE
Friendlier errors on post creation

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#85]
Post creation without a title gives you something like:

> The adapter rejected the commit because it was invalid

Ideally we should try to give the user a better error.

**Comment by begedin** [comment]
That's a general thing with non-validation adapter errors. From what I can tell, the default behavior of the JSON API adapter is the replace those errors with this generic one. I'll have to override a method in the application adapter, but we definitely should do this.
