### ISSUE TITLE
Switching to editing tab on posts/comments causes 422

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#86]
Switching to the editing tab on posts/comments causes a 422 error and "Loading preview..." to render. We should maybe not send the body at all in this case and just render a blank preview.

**Comment by begedin** [comment]
There should not be a validation error here at all. Did you test it with the correct API branch?

If so, then there's an issue somewhere I need to check.

Also, while I'm on it, we should probably improve the display logic there.

Right now, the content is set to "Loading preview" until we receive a valid response from the server, at which point, it's set to the content we receive in the response. If the response is not valid, it does nothing an gets stuck at "Loading preview"

**Comment by begedin** [comment]
This issue will likely be fixed API-side. When https://github.com/code-corps/code-corps-api/pull/219 is merged, we should revisit to check if there's still a problem.

**Comment by JoshSmith** [comment]
@begedin can you check status of this?

**Comment by JoshSmith** [comment]
@begedin ping.

**Comment by begedin** [comment]
I made the checks here, and while this specific issue (with a validation error) is gone, It's till not bulletproof.

If we click "new post", when just go immediately to preview, a request will be sent to the API with `markdown_preview` set to null, causing the API to fail with 

![image](https://cloud.githubusercontent.com/assets/1925540/13751015/667b8410-ea08-11e5-82a1-353e217caa5d.png)

If we focus the tab first, then "" will be sent as the `markdown_value`, so everything will work as expected. I think we should sanitize `markdown_preview` on the API side, so this one can be closed in favor of https://github.com/code-corps/code-corps-api/issues/256

**Comment by JoshSmith** [comment]
Okay, closing in favor of that issue.
