### ISSUE TITLE
Modify and test the payments/funds-recipient component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#868]
# Problem

The `payments/funds-recipient` component needs to be modified to have the following behavior, tested in an integration test.

Depending on the `stripeConnectAccount` model's `recipient_status`:

- `pending_requirement` - show just "Funds recipient" box with no other information, no fields, nothing; only the title
- `required` - renders the child `details-form` component
- `verifying` - render the `verification-document` and `personal-id-number` components
- `verified` - show the verified name of the individual, and the legal entity name if there is one

**Comment by pixelhandler** [comment]
@JoshSmith any links to docs on what the right data is?

**Comment by JoshSmith** [comment]
@pixelhandler I think this may be the hardest of the bunch right now. @begedin is going through and making notes about state for all of these. There already is the beginnings of a form here and the main tracking issue I think has some screenshots of a similar example flow with notes.

**Comment by JoshSmith** [comment]
@pixelhandler it's possible to work on this in conjunction with #884, but know that we may need to circle back and work on this again for `required` and `errored` states to check for the presence of that component in those cases.

**Comment by pixelhandler** [comment]
@JoshSmith  cool thanks :)

**Comment by pixelhandler** [comment]
Related work: #860, #884, #885, #886
