### ISSUE TITLE
Organization of files

### ISSUE THREAD

**Issue by hbrysiewicz** [code-corps/code-corps-ember#87]
It is beneficial to a project to keep a clear organizational pattern to the files themselves. In my experience this has been the following for ember-cli modules:

* static attributes
* service attributes
* aliased/one-line computed attributes
* computed properties
* methods
* actions

It is also my opinion that within each of those groups that the items be alphabetized but this only becomes noticeably beneficial when working with larger modules, which one might argue should potentially be broken up in smaller files at that point.

An example ember-cli component (totally foobar) with the aforementioned organizational style

```js
import Ember from 'ember';

export default Ember.Component.extend({
  classNames: ['example-component'],
  type: 'task',

  session: Ember.inject.service(),

  editing: Ember.computed.equal('mode', 'editing'),
  previewing: Ember.computed.equal('mode', 'previewing'),
  selectedItem: Ember.computed.alias('post')

  value: Ember.computed('selectedItem', function() {
    // ...
  }),

  didInitAttrs() {
    this._super(...arguments);
    this.mode = 'editing';
  },

  actions: {
    edit() {
      this.set('mode', 'editing');
    },

    preview() {
      this.set('mode', 'previewing');
      this.set('preview', 'Loading preview...');
      let content = this.get('input');
      this.sendAction('generatePreview', content);
    }
  }
});
```

**Comment by JoshSmith** [comment]
It would be really, really useful to take this and put into our `CONTRIBUTING.md` (once #89 is done) so that we have a style guide of sorts. Or break it out into a separate style guide, and add that to a components section.

There seems to be a list of components that we need to run through, then, to adopt these conventions.

**Comment by begedin** [comment]
I like the idea of organizing it this way to. I've sort of been following that general approach, but not always and not strictly, so agreeing on a set of rules and putting them "on paper" would help.
