### ISSUE TITLE
Add feature flags using Launch Darkly

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/code-corps-ember#905]
# Problem

Feature flags will help devOps, beta/canary testing, A/B testing, feature roll out and more. 

## References
https://launchdarkly.com/index.html
http://docs.launchdarkly.com/docs/js-sdk-reference

**Comment by JoshSmith** [comment]
I'm not positive that `ember-feature-flags` allows us to work with Launch Darkly?

**Comment by sarupbanskota** [comment]
@JoshSmith @rileytaylor new here; would you explain what Launch Darkly is? I'm working with `ember-feature-flags` on another project, so I can take this one up if we're doing it

**Comment by JoshSmith** [comment]
@sarupbanskota https://launchdarkly.com/

**Comment by rileytaylor** [comment]
@JoshSmith Ah. no. I didn't realize there was a difference between Launch Darkly and the other feature flags listed on that page. I'm editing the issue now.

**Comment by JoshSmith** [comment]
I looked into this more and it looks like there are some things we would need to handle. I'm waiting for some thoughts from the `ember-launch-darkly` folks here: https://github.com/kayako/ember-launch-darkly/issues/18

**Comment by JoshSmith** [comment]
We can generate anonymous user UUIDs with the following:

```
function uuidv4() {
  return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
    (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
  )
}
```

**Comment by rileytaylor** [comment]
That works, I've also had great success with https://www.npmjs.com/package/uuid if you want to be fully in uuid spec and not worry about it.
