### ISSUE TITLE
Get Mirage working in dev via some flag

### ISSUE THREAD

**Issue by hbrysiewicz** [code-corps/code-corps-ember#94]
Related to #74 - Allow for code-corps-ember to run in dev without needing the api running locally via ember-cli-mirage

**Comment by JoshSmith** [comment]
I think we can use the `passthrough` option with Mirage and set that up to work with our environment somehow. Need to find a way to activate it with some sort of `ember s` flag, but it seems doable from where I sit right now.

**Comment by JoshSmith** [comment]
Should we close this? @rileytaylor @WenInCode 

Believe it's worth doing so because we have `remote-development`, when that can be added.

If that's not an issue on API, can someone create it?

**Comment by rileytaylor** [comment]
It's already an issue https://github.com/code-corps/code-corps-api/issues/251

I'd say close, better to hit a remote api with the real thing. As cool as mirage is.

**Comment by JoshSmith** [comment]
Closed in favor of https://github.com/code-corps/code-corps-api/issues/251
