### ISSUE TITLE
Write proper model tests

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#98]
None of our models are really unit tested right now.

We should test, at least:

- [x] Category
- [x] Comment
- [x] Organization
- [x] OrganizationMembership
- [x] Preview
- [x] Project
- [x] ProjectCategory
- [x] ProjectSkill
- [x] Skill
- [x] Slugged route
- [x] Task
- [x] User
- [x] UserCategory
- [x] UserRole
- [x] UserSkill

And any computed properties they may have.

**Comment by begedin** [comment]
This might help

https://guides.emberjs.com/v2.3.0/testing/testing-models/

**Comment by filipecrosk** [comment]
@JoshSmith I think we're done here
