### ISSUE TITLE
Credit card number autofill on donation flow not working

### ISSUE THREAD

**Issue by iggyigner** [code-corps/code-corps-ember#994]
# Problem

When in Chrome, upon typing my CC number, it gave me the chrome popup to choose a CC I've pre-saved or previously used. When I clicked the card I wanted to use, the dialog disappeared but it didn't autofill the fields.

**Comment by JoshSmith** [comment]
This isn't debuggable in places where we don't use HTTPS, which means right now can only be debugged in production. Would be nice to find a way around this.

**Comment by JoshSmith** [comment]
This is now correctly fillable due to using `ember-stripe-elements`!
